#!/bin/bash
# potcar.spec の順に $VASP_PP_PATH/potpaw_PBE/<名前>/POTCAR を連結して POTCAR を作る (ADIT が生成)
# Concatenates the POTCARs listed in potcar.spec, in that order, into one POTCAR (generated by ADIT)
set -e
cd "$(dirname "$0")"
: "${VASP_PP_PATH:?VASP_PP_PATH が空です。POTCAR ライブラリの親ディレクトリを環境変数で指定してから実行してください / VASP_PP_PATH is empty: set it to the parent directory of the POTCAR library first}"
: > POTCAR
: > potcar.used
for name in Si; do
  f="$VASP_PP_PATH/potpaw_PBE/$name/POTCAR"
  [ -s "$f" ] || { echo "POTCAR がありません / no POTCAR at: $f" >&2; exit 1; }
  cat "$f" >> POTCAR
  printf '%s  %s  %s\n' "$name" "$(grep -m1 TITEL "$f" | sed 's/^ *//')" "$(grep -m1 ZVAL "$f" | sed 's/^ *//')" >> potcar.used
done
if command -v sha256sum >/dev/null 2>&1; then
  sha256sum POTCAR > potcar.sha256  # 作成時の記録: 組み立てた POTCAR の SHA-256 (中身の照合用のハッシュ。POTCAR 自体は配れないので値だけを残す)
fi
echo "POTCAR を作りました ($(grep -c TITEL POTCAR) 個。内訳は potcar.used) / wrote POTCAR ($(grep -c TITEL POTCAR) entries; see potcar.used)"
