
from __future__ import annotations

import argparse
import sys

from adit.analysis import AnalysisOptions, run_analysis
from adit.lang import L


COMMON_OPTIONS = (
    "--help-all", "--rdf", "--msd", "--dos", "--stride", "--skip", "-o", "--out", "--export",
    "--thermo", "--temperature", "--code", "--msd-fit", "--freq-scale", "--spectrum-measured", "--lang",
    "--plot-colors", "--plot-ticks", "--plot-grid", "--plot-spines", "--figure-format",
)
_HIDDEN: list = []


def _hide_detailed_options(parser, argv) -> None:
    if argv is not None and "--help-all" in argv:
        return
    import sys as _sys

    if argv is None and "--help-all" in _sys.argv[1:]:
        return
    for action in parser._actions:
        names = set(action.option_strings)
        if not names or names & set(COMMON_OPTIONS) or "--help" in names:
            continue
        _HIDDEN.append((action, action.help))
        action.help = argparse.SUPPRESS


def _show_all_options(parser) -> None:
    for action, text in _HIDDEN:
        action.help = text
    _HIDDEN.clear()
    parser.print_help()


def _msd_fit_range(values, parser):
    if not values:
        return None
    parts: list[str] = []
    for v in values:
        parts += [x for x in str(v).replace("、", ",").split(",") if x.strip()]
    try:
        nums = [float(x) for x in parts]
    except ValueError:
        parser.error(L("--msd-fit は数を 2 つ (例 --msd-fit 10 45 または --msd-fit 10,45) にしてください",
                       "--msd-fit takes two numbers (e.g. --msd-fit 10 45 or --msd-fit 10,45)"))
    if len(nums) != 2:
        parser.error(L(f"--msd-fit は数を 2 つ にしてください ({len(nums)} 個 受け取りました。例 --msd-fit 10,45)",
                       f"--msd-fit takes two numbers (got {len(nums)}; e.g. --msd-fit 10,45)"))
    if not nums[0] < nums[1]:
        parser.error(L(f"--msd-fit の始め ({nums[0]:g}) は終わり ({nums[1]:g}) より小さくしてください",
                       f"the start of --msd-fit ({nums[0]:g}) must be smaller than the end ({nums[1]:g})"))
    return (nums[0], nums[1])


def main(argv: list[str] | None = None) -> int:
    from adit.compat import ensure_printable_stdio

    ensure_printable_stdio()
    ap = argparse.ArgumentParser(
        prog="adit-analyze",
        description=L("計算結果のディレクトリを解析し、analysis/ に図と要約を書きます",
                      "analyze a calculation directory and write figures and a summary to analysis/"),
        epilog=L("ここに出ているのは よく使う指定 だけです。細かい指定 (配位数・Voronoi・自由エネルギー面など) は "
                 "adit-analyze --help-all で全部 出ます。何も付けずに実行しても、エネルギー・温度・結合長・"
                 "振動数・バンドは解析します。",
                 "Only the common options are listed here; run adit-analyze --help-all for every option. "
                 "With no options at all, the energy, temperature, bond lengths, frequencies and bands are still analyzed."))
    ap.add_argument("run_dir", help=L("計算結果のディレクトリ (ADIT が生成して、計算を実行したあとのもの)", "the calculation directory (generated by ADIT, after the calculation has run)"))
    ap.add_argument("--help-all", action="store_true", help=L(
        "細かい条件も含めて、すべての指定を表示します (既定の --help はよく使うものだけ)",
        "show every option, including the detailed ones (plain --help lists only the common ones)"))
    ap.add_argument("--rdf", action="store_true", help=L("動径分布関数 g(r) を元素の組ごとに求めます (MD の軌跡が要ります)", "radial distribution functions g(r) for each pair of elements (needs an MD trajectory)"))
    ap.add_argument("--msd", nargs="?", const="", default=None, metavar="ELEMENT",
                    help=L("平均二乗変位と拡散係数を求めます。元素記号を続けると、その元素だけ (例 --msd O)。省くと全原子",
                           "mean square displacement and diffusion coefficient; add an element symbol for that element only (e.g. --msd O), otherwise all atoms"))
    ap.add_argument("--dos", action="store_true", help=L("状態密度 (DOS) を描きます (DFTB+ の band.out、VASP の DOSCAR)", "density of states (DFTB+ band.out, VASP DOSCAR)"))
    ap.add_argument("--skip", type=int, default=0, metavar="N",
                    help=L("軌跡の最初の N フレームを平衡化の途中とみなして捨てます (RDF・MSD・平均温度に効きます。既定 0)",
                           "discard the first N trajectory frames as equilibration (affects RDF, MSD and mean temperature; default 0)"))
    ap.add_argument("--rmax", type=float, default=8.0, metavar="Å",
                    help=L("RDF を求める距離の上限 [Å] (既定 8)。周期系ではセルの一辺の半分までが目安の上限です",
                           "upper distance for the RDF in Å (default 8); for periodic cells, half the cell edge is the usual limit"))
    ap.add_argument("--sigma", type=float, default=0.1, metavar="eV",
                    help=L("DOS を広げるガウス関数の幅 [eV] (既定 0.1)", "width of the Gaussian that broadens the DOS, in eV (default 0.1)"))
    ap.add_argument("--stride", type=int, default=1, metavar="N",
                    help=L("軌跡を N フレームに 1 回だけ使います (N = 1 なら全フレーム。大きな軌跡の間引きで、RDF・MSD・z 方向の密度・書き出しに効きます)",
                           "use every N-th trajectory frame (N = 1 uses every frame; thins out large trajectories and affects RDF, MSD, z density and export)"))
    ap.add_argument("--msd-fit", type=str, nargs="+", default=None, metavar=("T0", "T1"),
                    help=L("拡散係数を当てはめる時間の範囲 [fs] (既定: 最大の遅れ時間の 10〜50 %%。後半は遅れ時間が長く、平均に使える時間原点が少ないので使いません)",
                           "time range in fs for fitting the diffusion coefficient (default: 10-50 %% of the maximum lag; lags in the second half are long and have the fewest time origins)"))
    ap.add_argument("--msd-axes", default="xyz", metavar="AXES",
                    help=L("MSD を取る成分 (既定 xyz = 3 次元で MSD = 6Dt。xy なら面内 2 次元で 4Dt、z なら 1 次元で 2Dt)",
                           "components used for the MSD (default xyz = 3D, MSD = 6Dt; xy gives in-plane 2D, 4Dt; z gives 1D, 2Dt)"))
    ap.add_argument("--msd-keep-drift", action="store_true",
                    help=L("MSD から系全体の重心の流れを落としません (既定は落とします。落とした量は要約に出ます)",
                           "do not remove the drift of the center of mass from the MSD (it is removed by default; the amount is given in the summary)"))
    ap.add_argument("--msd-blocks", type=int, default=5, metavar="N",
                    help=L("拡散係数の誤差を出すために軌跡を分ける区間の数 (既定 5。0 なら誤差を出しません)",
                           "number of equal blocks of the trajectory used for the error on the diffusion coefficient (default 5; 0 disables it)"))
    ap.add_argument("--coordination", type=float, default=0.0, metavar="Å", help=L(
        "原子ごとの配位数 (カットオフ [Å] を指定。ADIT は既定値を持ちません)",
        "coordination number per atom within the cutoff in Å (ADIT has no default)"))
    ap.add_argument("--centrosymmetry", nargs="?", const=12, type=int, default=0, metavar="N", help=L(
        "中心対称性パラメータ (相手の数。FCC なら 12、BCC なら 8)。欠陥かどうかは判定しません",
        "centrosymmetry parameter with N neighbours (12 for FCC, 8 for BCC); no defect judgement is made"))
    ap.add_argument("--steinhardt", type=float, default=0.0, metavar="Å", help=L(
        "Steinhardt の q4・q6 (カットオフ [Å])。どの値がどの構造かは言いません",
        "Steinhardt q4 and q6 within the cutoff in Å; ADIT does not say which structure a value means"))
    ap.add_argument("--clusters", type=float, default=0.0, metavar="Å", help=L(
        "カットオフ以内でつながった原子のかたまりの数と大きさ", "number and sizes of clusters connected within the cutoff in Å"))
    ap.add_argument("--adf", nargs="?", const="", default=None, metavar="中心[,外側]", help=L(
        "結合角の分布 (--adf O や --adf O,H)。カットオフは --adf-cutoff で指定します",
        "angle distribution (e.g. --adf O or --adf O,H); give the cutoff with --adf-cutoff"))
    ap.add_argument("--adf-cutoff", type=float, default=0.0, metavar="Å", help=L("結合角の分布のカットオフ [Å]", "cutoff in Å for the angle distribution"))
    ap.add_argument("--sq", action="store_true", help=L(
        "RDF から構造因子 S(q) を出す (--rdf が要ります)", "structure factor S(q) from the RDF (needs --rdf)"))
    ap.add_argument("--hbond", default="", metavar="距離,角度", help=L(
        "水素結合の本数 (例 --hbond 3.5,150)。**距離 [Å] と角度 [度] は必須**で、ADIT は既定値を持ちません",
        "count hydrogen bonds (e.g. --hbond 3.5,150); the distance in Å and the angle in degrees are required, with no defaults"))
    ap.add_argument("--rg", action="store_true", help=L("慣性半径 Rg の時系列", "time series of the radius of gyration"))
    ap.add_argument("--no-effective-mass", action="store_true", help=L(
        "バンドの端の有効質量を出しません (既定はバンド図があれば出します)",
        "do not compute the effective mass at the band edges (done by default when a band structure is present)"))
    ap.add_argument("--effective-mass-points", type=int, default=5, metavar="N", help=L(
        "有効質量の当てはめに使う k 点の数 (既定 5。奇数)", "number of k-points used to fit the effective mass (default 5, odd)"))
    ap.add_argument("--code", default="", metavar="NAME", help=L(
        "計算コードを自分で指定します (入力ファイルが無く、出力だけ手元にあるとき。例 --code gaussian)",
        "name the code yourself when only the output file is at hand and the input is missing (e.g. --code gaussian)"))
    ap.add_argument("--freq-scale", type=float, default=0.0, metavar="F", help=L(
        "振動数に掛ける補正係数 (例 0.96)。ADIT は既定値を持たず、使った値を図と要約に書きます",
        "scaling factor applied to the frequencies (e.g. 0.96); ADIT has no default and records the value you used"))
    ap.add_argument("--spectrum-measured", default="", metavar="FILE", help=L(
        "赤外・ラマンの図に重ねる測定の表 (1 列目 波数 [cm⁻¹]、2 列目 強度)。強度は最大値で規格化して重ねます",
        "measured spectrum to overlay on the IR and Raman plots (column 1 wavenumber in cm^-1, column 2 intensity); "
        "both are normalised to their maximum"))
    ap.add_argument("--plot-colors", default="", metavar="色,色,...", help=L(
        "図の線の色を順に使います (例 --plot-colors black,#1f77b4,tab:red)",
        "colors used for the lines, in order (e.g. --plot-colors black,#1f77b4,tab:red)"))
    ap.add_argument("--plot-ticks", default="", choices=("", "in", "out", "inout"), help=L(
        "目盛りの向き (in は内向き、out は外向き)", "tick direction (in, out or inout)"))
    ap.add_argument("--plot-grid", default="", choices=("", "both", "x", "y", "none"), help=L(
        "目盛り線を引く軸 (none なら引きません)", "which axes get grid lines (none draws no grid)"))
    ap.add_argument("--plot-spines", default="", choices=("", "all", "left-bottom", "none"), help=L(
        "グラフを囲む枠 (all は四方、left-bottom は左と下だけ)",
        "which spines are drawn (all, left and bottom only, or none)"))
    ap.add_argument("--plot-line-width", type=float, default=0.0, metavar="pt", help=L("線の太さ [pt]", "line width in points"))
    ap.add_argument("--plot-font-size", type=float, default=0.0, metavar="pt", help=L("図の文字の大きさ [pt]", "font size in the figures, in points"))
    ap.add_argument("--plot-dpi", type=int, default=0, metavar="dpi", help=L("図を保存する解像度 [dpi]", "resolution used when saving the figures"))
    ap.add_argument("--figure-format", default="", metavar="svg,pdf", help=L(
        "PNG に加えて出す図の形式 (svg / pdf / eps)。Word や LaTeX に貼るとき、拡大しても粗くなりません",
        "extra formats for the figures (svg, pdf, eps); these stay sharp when enlarged in Word or LaTeX"))
    ap.add_argument("--bader", default="", metavar="ACF.dat", help=L(
        "外部の bader (Henkelman、GPL) が書いた ACF.dat を読みます。ADIT は分割を計算しません",
        "read an ACF.dat written by the external bader program (Henkelman, GPL); ADIT does not do the partitioning"))
    ap.add_argument("--bader-valence", default="", metavar="4,6,1", help=L(
        "その価電子数 (原子の順に。VASP なら POTCAR の ZVAL、QE なら UPF の z_valence)。ADIT は推測しません",
        "valence electrons per atom in order (ZVAL in the POTCAR, z_valence in the UPF); ADIT does not guess them"))
    ap.add_argument("--displacement", nargs="?", const=1, type=int, default=0, metavar="N", help=L(
        "N 番目のフレームから最後までの変位 (既定は 1 番目)。原子の並びが同じ順であることが前提です",
        "displacement from frame N to the last one (default 1); this assumes the atom order is unchanged"))
    ap.add_argument("--strain", type=float, default=0.0, metavar="Å", help=L(
        "局所ひずみ (近傍のカットオフ [Å])。--displacement と一緒に使います",
        "local strain within the cutoff in Å; use it together with --displacement"))
    ap.add_argument("--voronoi", action="store_true", help=L(
        "Voronoi 多面体の体積と面の数 (最後の構造)", "Voronoi cell volumes and face counts for the last structure"))
    ap.add_argument("--voronoi-face-threshold", type=float, default=0.0, metavar="Å²", help=L(
        "数える面の面積の下限 [Å²] (小さい面を数えるかで面の数が変わります)",
        "smallest face area in Å² to count (the face count depends on this)"))
    ap.add_argument("--sasa", nargs="?", const="bondi,1.4", default="", metavar="表,プローブ", help=L(
        "溶媒接触表面積 (例 --sasa bondi,1.4)。半径の表とプローブ半径 [Å] は利用者が選びます",
        "solvent-accessible surface area (e.g. --sasa bondi,1.4); you choose the radii set and the probe radius in Å"))
    ap.add_argument("--pca", nargs="?", const=3, type=int, default=0, metavar="N", help=L(
        "フレームの主成分分析 (成分の数。既定 3)。重ね合わせてから計算します",
        "PCA over the frames with N components (default 3), after superposition"))
    ap.add_argument("--cluster", type=int, default=0, metavar="K", help=L(
        "主成分の上で k-means。群の数 K は利用者が決めます (ADIT はいくつが正しいか言いません)",
        "k-means on the principal components; you choose the number of groups K"))
    ap.add_argument("--fes", type=float, default=0.0, metavar="K", help=L(
        "距離・角度・二面角の時系列から自由エネルギー面 A = -kT ln P (温度 [K] を渡します)。1 つなら 1 次元、2 つなら 2 次元",
        "free-energy surface A = -kT ln P from the requested distance/angle/dihedral series at the given temperature in K"))
    ap.add_argument("--fes-bins", type=int, default=50, metavar="N", help=L("自由エネルギー面の区間の数 (既定 50)", "number of bins for the free-energy surface (default 50)"))
    ap.add_argument("--fes-unit", choices=("kJ/mol", "kcal/mol", "eV"), default="kJ/mol", help=L("自由エネルギーの単位 (既定 kJ/mol)", "unit for the free energy (default kJ/mol)"))
    ap.add_argument("--density-grid", nargs="?", const="48,48,48", default="", metavar="Nx,Ny,Nz", help=L(
        "3 次元の数密度を積んで cube に書き出す (VMD・VESTA・OVITO 用)", "accumulate a 3D number density and write a cube file (for VMD, VESTA, OVITO)"))
    ap.add_argument("--zdens-axis", choices=("a", "b", "c"), default="c", help=L(
        "密度分布を取る軸 (既定 c)。界面が a 面や b 面に平行な系で使います",
        "axis for the density profile (default c); use it when the interface is normal to a or b"))
    ap.add_argument("--select", default="", metavar="式", help=L(
        "原子の選び方 (例: \"element O\"、\"index 1-10\"、\"z < 10\"、\"within 5 of index 3\"、and / or / not)。MSD・変位の分布・VACF に効きます",
        "how to select atoms (e.g. \"element O\", \"index 1-10\", \"z < 10\", \"within 5 of index 3\", and/or/not); applies to MSD, the displacement distribution and the VACF"))
    ap.add_argument("--distance", action="append", default=[], metavar="i,j", help=L(
        "2 原子の距離の時系列 (1 始まりの番号。複数回書けます)", "time series of the distance between two atoms (1-based indices; repeatable)"))
    ap.add_argument("--angle", action="append", default=[], metavar="i,j,k", help=L(
        "3 原子の角度の時系列 (j が頂点)", "time series of the angle i-j-k (j is the vertex)"))
    ap.add_argument("--dihedral", action="append", default=[], metavar="i,j,k,l", help=L(
        "4 原子の二面角の時系列", "time series of the dihedral i-j-k-l"))
    ap.add_argument("--rmsd", nargs="?", const=1, type=int, default=0, metavar="基準", help=L(
        "基準のフレーム (1 始まり、既定 1) からの RMSD の時系列 (Kabsch で重ね合わせ)",
        "time series of the RMSD from a reference frame (1-based, default 1), after a Kabsch superposition"))
    ap.add_argument("--rmsf", action="store_true", help=L(
        "原子ごとの揺らぎ RMSF", "per-atom fluctuation (RMSF)"))
    ap.add_argument("--msd-per-atom", action="store_true", help=L(
        "原子 1 個ごとの拡散係数も出す (イオン伝導体で「どの原子が動くか」を見るとき)。速い・遅いの判定はしません",
        "also report a diffusion coefficient for each atom (useful for ion conductors); no fast/slow judgement is made"))
    ap.add_argument("--vacf", action="store_true", help=L(
        "速度自己相関 (VACF) と振動スペクトルを出す (軌跡に速度が無ければ座標の差分で作ります)",
        "compute the velocity autocorrelation (VACF) and the vibrational spectrum (velocities are made by finite differences if absent)"))
    ap.add_argument("--conductivity", type=float, default=0.0, metavar="電荷", help=L(
        "拡散係数からイオン伝導度 (Nernst-Einstein) を出す。イオンの電荷を指定します (Na なら 1)。ADIT は酸化数を決めません",
        "compute the ionic conductivity (Nernst-Einstein) from the diffusion coefficient; give the ionic charge (1 for Na). ADIT does not assign oxidation states"))
    ap.add_argument("--conductivity-temperature", type=float, default=0.0, metavar="K", help=L(
        "伝導度の温度 [K] (省くと入力の設定温度、無ければ出力の平均温度)",
        "temperature in K for the conductivity (default: the target temperature in the input, else the mean temperature in the output)"))
    ap.add_argument("--vanhove", nargs="?", const=100, type=int, default=0, metavar="N", help=L(
        "変位の分布 (van Hove の自己相関) から D(τ) と非ガウス因子を出す。N は見る遅れ時間の点数 (既定 100)",
        "obtain D(tau) and the non-Gaussian parameter from the displacement distribution (van Hove self-part); N is the number of lag times (default 100)"))
    ap.add_argument("--write-msd-job", nargs="?", const=".", default=None, metavar="DIR", help=L(
        "重い解析を実行用のファイル一式 (msd_worker.py と msd_run.sh) を書き出して終わる (既定はこのディレクトリ)",
        "write the files to run the heavy analysis (msd_worker.py and msd_run.sh) and stop (default: this directory)"))
    ap.add_argument("--vanhove-here", action="store_true", help=L(
        "重くてもこの場で計算する (既定は、見積もりが 60 秒を超えたら実行用のファイルを置くだけ)",
        "compute it here even when heavy (by default, files to run it are written when the estimate exceeds 60 s)"))
    ap.add_argument("--heavy-limit", type=float, default=60.0, metavar="秒", help=L(
        "この場で計算してよい見積もりの上限 [秒] (既定 60)", "limit in seconds for computing here (default 60)"))
    ap.add_argument("--vanhove-displacement", choices=("mic", "unwrapped"), default="mic", help=L(
        "変位の測り方: mic = 折り返した座標の最小像 (セルの幅の半分で頭打ち)、unwrapped = 巻き戻した座標の差",
        "how displacements are measured: mic = minimum image of the wrapped coordinates (capped at half the cell width), unwrapped = difference of unwrapped coordinates"))
    ap.add_argument("--zdens", nargs="?", const=0.2, default=None, type=float, metavar="Å",
                    help=L("z 方向 (a-b 面に垂直な方向) の元素ごとの密度分布を描きます。数を続けると区間の幅 [Å] (既定 0.2)。周期系だけ",
                           "density profile of each element along z (normal to the a-b plane); an optional number sets the bin width in Å (default 0.2); periodic systems only"))
    ap.add_argument("--viscosity", action="store_true", help=L(
        "圧力テンソルの非対角成分から、Green-Kubo の式で粘度を求めます (いま対応しているのは LAMMPS だけ。"
        "収束の判定はしません。図で確かめてください)",
        "viscosity from the off-diagonal pressure components with the Green-Kubo relation (LAMMPS only for now; "
        "convergence is not judged, read it off the figure)"))
    ap.add_argument("--plane-average", nargs="?", const="c", default=None, metavar="AXIS", help=L(
        "体積データ (VASP の LOCPOT・CHGCAR、*.cube) を、軸に垂直な面で平均した分布にします (既定は c 軸)。図と CSV を書きます",
        "average volumetric data (VASP LOCPOT/CHGCAR, *.cube) over planes normal to an axis (default c); writes a figure and a CSV"))
    ap.add_argument("-o", "--out-dir", default=None, metavar="DIR", help=L(
        "図・表・要約の書き出し先 (既定は <計算のディレクトリ>/analysis/)。計算のディレクトリを変えずに解析したいときに使う",
        "where to write figures, tables and the summary (default <run directory>/analysis/); use it to leave the run directory untouched"))
    ap.add_argument("--eyring", action="append", default=[], metavar="kJ/mol", help=L(
        "活性化自由エネルギー ΔG‡ [kJ/mol] から Eyring の式で速度定数を出す (複数回書ける)。どの差が ΔG‡ かは利用者が決める",
        "compute a rate constant from an activation free energy dG# in kJ/mol using the Eyring equation (repeatable); you decide which difference is the barrier"))
    ap.add_argument("--eyring-temperature", type=float, default=298.15, metavar="K", help=L("Eyring の式の温度 [K] (既定 298.15)", "temperature in K for the Eyring equation (default 298.15)"))
    ap.add_argument("--eyring-kappa", type=float, default=1.0, metavar="KAPPA", help=L("透過係数 κ (既定 1。トンネル効果は入れない)", "transmission coefficient kappa (default 1; no tunnelling correction)"))
    ap.add_argument("--xrd", nargs="?", const="CuKa", default="", metavar="RADIATION", help=L(
        "最終構造 (周期系) から粉末 X 線回折のパターンを計算する (既定の線源 CuKa。pymatgen が要る)",
        "compute a powder XRD pattern from the final (periodic) structure (default radiation CuKa; needs pymatgen)"))
    ap.add_argument("--xrd-range", default="5,90", metavar="LO,HI", help=L("粉末回折の 2θ の範囲 [度]", "2-theta range for the powder pattern, in degrees"))
    ap.add_argument("--xrd-measured", default=None, metavar="FILE", help=L(
        "重ねて描く測定のパターン (1 列目 2θ [度]、2 列目 強度。カンマか空白区切り)。一致は判定しない",
        "a measured pattern to overlay (column 1: 2-theta in degrees, column 2: intensity); agreement is not assessed"))
    ap.add_argument("--cube-unit", choices=("ev", "ry", "hartree"), default="", help=L(
        "cube の値の単位 (ファイルには書かれていません。QE の pp.x は Ry、Gaussian は Hartree のことが多い)。"
        "指定すると仕事関数も出せます",
        "unit of the values in a cube file (not recorded in the file; QE pp.x usually writes Ry, Gaussian Hartree); "
        "giving it also enables the work function"))
    ap.add_argument("--work-function", action="store_true", help=L(
        "面平均の最大値 (真空準位) とフェルミ準位から仕事関数を出します (--plane-average と一緒に使います。真空の領域があるかは判定しません)",
        "work function from the maximum of the plane-averaged profile (vacuum level) and the Fermi level "
        "(use with --plane-average; whether a vacuum region exists is not judged)"))
    ap.add_argument("--export", action="store_true",
                    help=L("軌跡を analysis/export/ に書き出します (trajectory.extxyz / .xyz / .pdb、VMD の view.vmd、OVITO の ovito_pipeline.py、説明の export_README.txt)",
                           "write the trajectory to analysis/export/ (trajectory.extxyz / .xyz / .pdb, VMD view.vmd, OVITO ovito_pipeline.py, export_README.txt)"))
    ap.add_argument("--unwrap-molecules", action="store_true",
                    help=L("書き出す前に、分子を周期境界でつなぎ直します (最初のフレームの結合で分子を決め、最後まで同じ区切りを使います)",
                           "make molecules whole across periodic boundaries before writing (molecules are taken from the bonds of the first frame and kept)"))
    ap.add_argument("--memory-mb", type=float, default=None, metavar="MB",
                    help=L("MSD で座標を持つメモリの上限 [MB] (既定 1024。メモリ 8 GB の PC を基準にした値)",
                           "memory limit in MB for the coordinates held by the MSD (default 1024, chosen for a PC with 8 GB of memory)"))
    ap.add_argument("--scan", action="store_true", help=L(
        "adit-gen --scan で作ったディレクトリ (中に scan.json) の各計算の最終エネルギーを集め、値とエネルギーの表 scan_energies.csv を書きます",
        "for a directory made by adit-gen --scan (with scan.json inside), collect the final energy of each run into scan_energies.csv"))
    ap.add_argument("--audit-with", action="append", default=[], metavar="DIR", help=L(
        "別コードの計算ディレクトリを加え、MSD またはエネルギーを比べる前に原子・セル・時間の機械的な整合性を点検します (複数回指定可。書き込みなし)",
        "add another run directory and check atom, cell, and time consistency before cross-code MSD or energy comparison (repeatable; read-only)"))
    ap.add_argument("--audit-kind", choices=("msd", "energy"), default="msd", help=L(
        "--audit-with の点検対象: msd (既定) または energy",
        "what --audit-with checks: msd (default) or energy"))
    ap.add_argument("--compare", nargs="?", const="", default=None, metavar="REACTIONS", help=L(
        "組にして比べる表。「名前=係数:ディレクトリ,…」(係数は生成したファイルが正、反応物が負。反応は ; で区切る。ディレクトリは run_dir からの相対パス)。"
        "値を省くと run_dir/compare.json を読む。例 --compare \"ads=1:slab_mol,-1:slab,-1:mol\"",
        "table comparing runs: name=coef:dir,... (products positive, reactants negative; separate reactions with ;; dirs relative to run_dir). "
        "Without a value, run_dir/compare.json is read. e.g. --compare \"ads=1:slab_mol,-1:slab,-1:mol\""))
    from adit.analysis.thermo import GEOMETRIES, MODELS
    ap.add_argument("--thermo", choices=MODELS, default=None, help=L(
        "振動数から熱化学を ASE で計算するモデル。温度などは下の欄で指定する (既定は置きません。足りなければ理由を出して計算しません)",
        "model for thermochemistry from the frequencies (ASE); give the inputs below (no defaults; if something is missing, the reason is shown)"))
    ap.add_argument("--temperature", default=None, metavar="K[,K...]", help=L("熱化学の温度 [K] (カンマで複数)", "temperature(s) for thermochemistry in K (comma separated)"))
    ap.add_argument("--pressure", type=float, default=None, metavar="Pa", help=L("理想気体の圧力 [Pa] (1 atm = 101325、1 bar = 100000)", "ideal-gas pressure in Pa (1 atm = 101325, 1 bar = 100000)"))
    ap.add_argument("--symmetry-number", type=int, default=None, metavar="N", help=L("回転の対称数 (理想気体)", "rotational symmetry number (ideal gas)"))
    ap.add_argument("--geometry", choices=GEOMETRIES, default=None, help=L("分子の形 (理想気体)", "molecular geometry (ideal gas)"))
    ap.add_argument("--spin", type=float, default=None, metavar="S", help=L("全スピン S (理想気体。一重項 0、二重項 0.5)", "total spin S (ideal gas; singlet 0, doublet 0.5)"))
    ap.add_argument("--imaginary", choices=("ignore", "stop"), default=None, help=L("使うモードに虚振動があるとき: 除いて計算 (ignore) / 計算しない (stop)", "if imaginary modes are among the modes used: drop them (ignore) / do not compute (stop)"))
    ap.add_argument("--exclude-lowest", type=int, default=None, metavar="N", help=L("調和・準調和・準 RRHO で除く低い振動の本数", "number of lowest modes to exclude (harmonic, quasi-harmonic, quasi-RRHO)"))
    ap.add_argument("--qh-cutoff", type=float, default=None, metavar="cm-1", help=L("準調和の下限の振動数 [cm^-1]", "quasi-harmonic cutoff frequency in cm^-1"))
    ap.add_argument("--msrrho-tau", type=float, default=None, metavar="cm-1", help=L("準 RRHO (Grimme) の減衰の τ [cm^-1]", "quasi-RRHO (Grimme) damping tau in cm^-1"))
    ap.add_argument("--uvvis", default=None, metavar="SHAPE:FWHM", help=L("ORCA の TD-DFT の吸収を広げる形と半値全幅 [eV] (例 gauss:0.3、lorentz:0.2)", "shape and FWHM in eV for broadening ORCA TD-DFT absorption (e.g. gauss:0.3, lorentz:0.2)"))
    ap.add_argument("--pdos", action="store_true", help=L("PDOS が描けないときも理由を要約に書く (ファイルがあれば、指定しなくても描きます)", "report why no PDOS is drawn (PDOS is drawn whenever the files exist)"))
    ap.add_argument("--collect", action="store_true", help=L(
        "フォノン (phonon_collect.py) と弾性定数 (elastic_collect.py) の集計を、まだしていなければここから行います "
        "(各ディレクトリの出力を読んで band.yaml や C_ij を書くだけで、計算は実行しません)",
        "run the phonon (phonon_collect.py) and elastic (elastic_collect.py) collections here if it has not been done "
        "(it only reads the outputs of each directory and writes band.yaml or C_ij; no calculation is started)"))
    ap.add_argument("--no-compare", action="store_true", help=L(
        "compare.json があっても、組にして比べる表を出しません (既定は、あれば出します)",
        "do not write the comparison table even if compare.json is present (by default it is written when the file exists)"))
    ap.add_argument("--symprec", default=None, metavar="Å[,Å...]", help=L("空間群の許容誤差 [Å] (カンマで複数。既定 1e-5,1e-3,1e-1 を並べる)", "space-group tolerance(s) in Å (comma separated; default lists 1e-5,1e-3,1e-1)"))
    import sys as _sys

    if "--help-all" in (argv if argv is not None else _sys.argv[1:]):
        ap.epilog = L("何も付けずに実行しても、エネルギー・温度・結合長・振動数・バンドは解析します。",
                      "With no options at all, the energy, temperature, bond lengths, frequencies and bands are still analyzed.")
        ap.print_help()
        return 0
    _hide_detailed_options(ap, argv)
    a = ap.parse_args(argv)
    if a.audit_with:
        ignored = [name for name, active in (
            ("--compare", a.compare is not None), ("--scan", a.scan),
            ("--rdf", a.rdf), ("--msd", a.msd is not None), ("--dos", a.dos),
            ("--zdens", a.zdens is not None), ("--export", a.export),
            ("--unwrap-molecules", a.unwrap_molecules), ("--thermo", a.thermo is not None),
            ("--uvvis", a.uvvis is not None), ("--pdos", a.pdos),
            ("--collect", a.collect), ("--no-compare", a.no_compare),
            ("--skip", a.skip != 0), ("--stride", a.stride != 1),
            ("--rmax", a.rmax != 8.0), ("--sigma", a.sigma != 0.1),
            ("--msd-fit", a.msd_fit is not None), ("--msd-axes", a.msd_axes != "xyz"),
            ("--msd-keep-drift", a.msd_keep_drift), ("--msd-blocks", a.msd_blocks != 5),
            ("--memory-mb", a.memory_mb is not None), ("--symprec", a.symprec is not None),
            ("--temperature", a.temperature is not None), ("--pressure", a.pressure is not None),
            ("--symmetry-number", a.symmetry_number is not None), ("--geometry", a.geometry is not None),
            ("--spin", a.spin is not None), ("--imaginary", a.imaginary is not None),
            ("--exclude-lowest", a.exclude_lowest is not None), ("--qh-cutoff", a.qh_cutoff is not None),
            ("--msrrho-tau", a.msrrho_tau is not None),
        ) if active]
        if ignored:
            options = ", ".join(ignored)
            print(L(f"--audit-with は読み取り専用の点検だけを行います。{options} は同時に使えません。",
                    f"--audit-with performs only a read-only audit; it cannot be combined with {options}."), file=sys.stderr)
            return 1
        from adit.analysis import audit_run_dirs
        try:
            audit = audit_run_dirs([a.run_dir, *a.audit_with], require_md=a.audit_kind == "msd")
        except (OSError, ValueError) as ex:
            print(L(f"横断点検ができません: {ex}", f"cannot audit the runs: {ex}"), file=sys.stderr)
            return 1
        print(audit.summary_text())
        return 0 if audit.comparable else 1
    if any(arg == "--audit-kind" or arg.startswith("--audit-kind=") for arg in (argv if argv is not None else sys.argv[1:])):
        print(L("--audit-kind は --audit-with と一緒に指定してください",
                "--audit-kind requires --audit-with"), file=sys.stderr)
        return 1
    if a.compare is not None:
        from adit.analysis.compare import CompareError, analyze_compare, parse_compare
        try:
            cres = analyze_compare(a.run_dir, parse_compare(a.compare) if a.compare.strip() else None)
        except (CompareError, ValueError, OSError) as ex:
            print(L(f"比べられません: {ex}", f"cannot compare: {ex}"), file=sys.stderr)
            return 1
        print(cres.summary_text())
        for name, path in {**cres.files, **cres.figures}.items():
            print(f"{name}: {path}")
        return 0
    if a.scan:
        from adit.scan import SCAN_FILE, analyze_scan
        from pathlib import Path
        if not (Path(a.run_dir) / SCAN_FILE).is_file():
            print(L(f"{a.run_dir} に {SCAN_FILE} がありません (adit-gen --scan で作ったディレクトリを指定します)",
                    f"{a.run_dir} has no {SCAN_FILE} (give a directory made by adit-gen --scan)"), file=sys.stderr)
            return 1
        try:
            res = analyze_scan(a.run_dir)
        except Exception as ex:
            print(L(f"集計できません: {ex}", f"cannot collect the results: {ex}"), file=sys.stderr)
            return 1
        print(res.summary_text())
        for name, path in res.figures.items():
            print(L(f"図 ({name}): {path}", f"figure ({name}): {path}"))
        return 0
    if a.write_msd_job is not None:
        from adit.analysis import heavy_setup

        written = heavy_setup.write_job(a.write_msd_job, dt_fs=a.dt if getattr(a, "dt", None) else 1.0,
                                        species=(a.msd or None), taus=int(a.vanhove or 100),
                                        displacement=a.vanhove_displacement)
        print(L("重い解析を実行用のファイルを書きました:", "wrote the files to run the heavy analysis:"))
        for path in written:
            print(f"  {path}")
        print(L(f"  実行すると {heavy_setup.RESULT_FILE} ができます。そのあと adit-analyze <ディレクトリ> で図になります",
                f"  running them writes {heavy_setup.RESULT_FILE}; then adit-analyze <directory> turns it into figures"))
        return 0
    from adit.results import not_run_yet
    if not_run_yet(a.run_dir):
        print(L(f"{a.run_dir} には計算の出力がありません。まだ実行していないようです "
                f"(このディレクトリで bash submit.sh を実行してから、もう一度 adit-analyze を実行してください)。",
                f"{a.run_dir} contains no output of a calculation; it looks like it has not been run yet "
                f"(run bash submit.sh in this directory first, then run adit-analyze again)."), file=sys.stderr)
        return 2
    try:
        thermo_opts = _thermo_options(a)
        uv = _uvvis(a.uvvis)
        from adit.analysis.symmetry import DEFAULT_SYMPRECS
        symprecs = _floats(a.symprec) if a.symprec else DEFAULT_SYMPRECS
        from adit.analysis.compute import parse_axes
        parse_axes(a.msd_axes)
    except ValueError as ex:
        print(str(ex), file=sys.stderr)
        return 1
    try:
        from adit.analysis.trajectory import MEMORY_BUDGET_MB
        res = run_analysis(a.run_dir, AnalysisOptions(out_dir=a.out_dir, msd_per_atom=a.msd_per_atom, zdens_axis=a.zdens_axis,
                                                      select=a.select, distances=a.distance, angles=a.angle,
                                                      dihedrals=a.dihedral, rmsd_reference=a.rmsd, rmsf=a.rmsf, coordination_cutoff=a.coordination, centrosymmetry_neighbors=a.centrosymmetry,
                                                      steinhardt_cutoff=a.steinhardt, cluster_cutoff=a.clusters,
                                                      adf=a.adf, adf_cutoff=a.adf_cutoff, structure_factor=a.sq,
                                                      hbond=a.hbond, radius_of_gyration=a.rg, density_grid=a.density_grid,
                                                      effective_mass=not a.no_effective_mass,
                                                      effective_mass_points=a.effective_mass_points,
                                                      bader=a.bader, bader_valence=a.bader_valence,
                                                      displacement_reference=a.displacement, strain_cutoff=a.strain,
                                                      voronoi=a.voronoi, voronoi_face_threshold=a.voronoi_face_threshold,
                                                      sasa=a.sasa, pca=a.pca, cluster=a.cluster,
                                                      fes_temperature_k=a.fes, fes_bins=a.fes_bins, fes_unit=a.fes_unit,
                                                      code=a.code, freq_scale=a.freq_scale,
                                                      plot_colors=a.plot_colors, plot_ticks=a.plot_ticks,
                                                      plot_grid=a.plot_grid, plot_spines=a.plot_spines,
                                                      plot_line_width=a.plot_line_width,
                                                      plot_font_size=a.plot_font_size, plot_dpi=a.plot_dpi,
                                                      figure_format=a.figure_format,
                                                      spectrum_measured=a.spectrum_measured,
                                                      vacf=a.vacf, conductivity_charge=a.conductivity, conductivity_temperature_k=a.conductivity_temperature,
                                                      vanhove=a.vanhove, vanhove_displacement=a.vanhove_displacement, vanhove_here=a.vanhove_here, heavy_limit_seconds=a.heavy_limit, xrd=a.xrd, xrd_range=_floats(a.xrd_range)[:2] or (5.0, 90.0), xrd_measured=a.xrd_measured, cube_unit=a.cube_unit, viscosity=a.viscosity, plane_average=a.plane_average or ("c" if a.work_function else None),
                                                      work_function=a.work_function, rdf=a.rdf, msd=a.msd is not None, msd_species=(a.msd or None), dos=a.dos,
                                                      skip_frames=a.skip, rdf_rmax=a.rmax, dos_sigma=a.sigma, stride=a.stride,
                                                      msd_fit_fs=_msd_fit_range(a.msd_fit, ap),
                                                      msd_axes=a.msd_axes, msd_remove_drift=not a.msd_keep_drift,
                                                      msd_error_blocks=a.msd_blocks,
                                                      zdens=a.zdens is not None, zdens_bin_ang=a.zdens or 0.2,
                                                      export=a.export or a.unwrap_molecules, export_unwrap=a.unwrap_molecules,
                                                      memory_budget_mb=a.memory_mb if a.memory_mb else MEMORY_BUDGET_MB,
                                                      thermo=thermo_opts, uvvis_broadening=uv, pdos=a.pdos, symprecs=symprecs,
                                                      compare=not a.no_compare, collect=a.collect))
    except Exception as ex:
        print(str(ex), file=sys.stderr)
        from adit.results import failure_note
        note = failure_note(a.run_dir)
        if note:
            print(note, file=sys.stderr)
        return 1
    print(res.summary_text())
    if a.eyring:
        from adit.analysis.rate import RateError, eyring_rate, summary_line

        for text in a.eyring:
            try:
                result = eyring_rate(float(text), a.eyring_temperature, a.eyring_kappa)
            except (ValueError, RateError) as ex:
                print(str(ex), file=sys.stderr)
                return 1
            print(summary_line(result))
            print("  " + result.note)
    return 0


def _floats(text: str) -> tuple[float, ...]:
    try:
        return tuple(float(x) for x in text.split(",") if x.strip())
    except ValueError as ex:
        raise ValueError(L(f"数をカンマで区切って書いてください: {text!r}", f"write numbers separated by commas: {text!r}")) from ex


def _thermo_options(a):
    if a.thermo is None:
        return None
    from adit.analysis.thermo import ThermoOptions
    return ThermoOptions(model=a.thermo, temperatures_k=_floats(a.temperature) if a.temperature else (), pressure_pa=a.pressure,
                         symmetry_number=a.symmetry_number, geometry=a.geometry, spin=a.spin, imaginary=a.imaginary,
                         exclude_lowest=a.exclude_lowest, qh_cutoff_cm1=a.qh_cutoff, msrrho_tau_cm1=a.msrrho_tau)


def _uvvis(text: str | None) -> tuple[str, float] | None:
    if not text:
        return None
    from adit.analysis.uvvis import SHAPES
    shape, _, w = text.partition(":")
    try:
        fwhm = float(w)
    except ValueError:
        fwhm = None
    if shape.strip() not in SHAPES or fwhm is None or fwhm <= 0:
        raise ValueError(L(f"--uvvis は「形:半値全幅」の形です (形は {' / '.join(SHAPES)}、幅は正の数 [eV]。例 gauss:0.3): {text!r}",
                           f"--uvvis takes shape:FWHM (shape {' / '.join(SHAPES)}, positive width in eV; e.g. gauss:0.3): {text!r}"))
    return shape.strip(), fwhm


if __name__ == "__main__":
    sys.exit(main())
