"""Write heavy analyses as job files instead of running them inside the application."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from adit.lang import L

WORKER_FILE = "msd_worker.py"
JOB_FILE = "msd_run.sh"
RESULT_FILE = "msd_vanhove.json"
CELL_FILE = "msd_cell.txt"

SECONDS_PER_DISPLACEMENT = 1.0e-7
SECONDS_PER_TAU_FIT = 5.0e-3
BYTES_PER_ATOM_FRAME = 24


def estimate(frames: int, atoms: int, taus: int = 100, displacement: str = "mic") -> dict:
    frames, atoms, taus = max(int(frames), 0), max(int(atoms), 0), max(int(taus), 0)
    displacements = 0.75 * taus * frames * atoms
    images = 27 if displacement == "mic" else 1
    seconds = displacements * SECONDS_PER_DISPLACEMENT * (images / 27) + taus * SECONDS_PER_TAU_FIT
    coords_mb = frames * atoms * BYTES_PER_ATOM_FRAME / 1e6
    return {"frames": frames, "atoms": atoms, "taus": taus, "displacements": int(displacements),
            "seconds": float(seconds), "coordinates_mb": float(coords_mb),
            "note": L("見積もりです (実際には計算していません)。係数は 2026-09-13 に手元で測った値",
                      "an estimate (nothing was computed); the constants were measured on 2026-09-13")}


def is_heavy(frames: int, atoms: int, taus: int = 100, limit_seconds: float = 60.0) -> bool:
    return estimate(frames, atoms, taus)["seconds"] > limit_seconds


def worker_source() -> str:
    # A frozen executable keeps modules in an archive, so read the worker as package data first.
    try:
        from importlib.resources import files

        return files("adit.analysis").joinpath(WORKER_FILE).read_text(encoding="utf-8")
    except Exception:
        return (Path(__file__).resolve().parent / WORKER_FILE).read_text(encoding="utf-8")


def write_job(run_dir: Path | str, *, dt_fs: float | None, species: str | None = None, taus: int = 100,
              displacement: str = "mic", natoms: int = 0, trajectory: str = "", cell_file: str = "",
              cell=None, profile=None, spec=None) -> list[Path]:
    """Write the files for a heavy analysis into a run directory and return the written paths. With profile and spec the job script is for a cluster; otherwise it runs locally. Nothing is submitted."""
    out = Path(run_dir).expanduser()
    out.mkdir(parents=True, exist_ok=True)
    (out / WORKER_FILE).write_text(worker_source(), encoding="utf-8", newline="\n")
    written = [out / WORKER_FILE]
    if cell is not None and not cell_file:
        rows = np.asarray(cell, dtype=float).reshape(3, 3)
        (out / CELL_FILE).write_text("".join(f"TV {v[0]:.10f} {v[1]:.10f} {v[2]:.10f}\n" for v in rows), encoding="utf-8", newline="\n")
        cell_file = CELL_FILE
        written.append(out / CELL_FILE)
    dt_known = dt_fs is not None and dt_fs > 0
    args = [WORKER_FILE, trajectory or "<軌跡のファイル>", f"--dt {dt_fs:g}" if dt_known else "--dt <1フレームの時間 fs>",
            f"--taus {taus}", f"--displacement {displacement}"]
    if natoms:
        args.append(f"--natoms {natoms}")
    if cell_file:
        args.append(f"--cell {cell_file}")
    if species:
        args.append(f"--species {species}")
    command = "python " + " ".join(args)
    body = [
        "#!/bin/bash",
        L("# ADIT が生成した、重い解析を実行する手順。ADIT は投入しません。人が実行します。",
          "# Generated by ADIT to run the heavy analysis. ADIT does not submit it; a human runs it."),
        L(f"# 走り終わると {RESULT_FILE} ができます。図にするのは adit-analyze <このディレクトリ> です。",
          f"# It writes {RESULT_FILE}; plot it with adit-analyze <this directory>."),
        L("# 要るもの: numpy と scipy だけ (ADIT は要りません)。",
          "# Requirements: numpy and scipy only (ADIT is not needed)."),
    ]
    if not trajectory:
        body.append(L("# <軌跡のファイル> を、この場所にある軌跡の名前に置き換えてください。",
                      "# Replace <軌跡のファイル> with the name of the trajectory file in this directory."))
    if not dt_known:
        body.append(L("# 1 フレームの時間 [fs] が出力から読めなかったので --dt は穴です。値を入れてから実行してください。",
                      "# The time per frame in fs could not be read from the output; fill in --dt before running."))
    if cell_file == CELL_FILE:
        body.append(L(f"# {CELL_FILE} は ADIT が最後のフレームのセルを書いたもの (TV の行が 3 本)。軌跡にセルが無くても境界越えを巻き戻せます。",
                      f"# {CELL_FILE} holds the cell of the last frame (three TV rows), so boundary crossings are unwrapped even when the trajectory has no cell."))
    body += ['cd "$(dirname "$0")"', command, ""]
    text = "\n".join(body)
    if profile is not None and spec is not None:
        from adit.scripts.render import render_submit

        try:
            text = render_submit(spec, profile, command)
        except Exception:
            pass
    path = out / JOB_FILE
    path.write_text(text, encoding="utf-8", newline="\n")
    try:
        path.chmod(0o755)
    except OSError:
        pass
    return written + [path]


def readme_lines(estimate_info: dict) -> list[str]:
    return [
        L(f"  {JOB_FILE}    重い解析 (原子ごとの拡散係数・変位の分布) を実行する手順。見積もり "
          f"{estimate_info['seconds']:.0f} 秒、座標 {estimate_info['coordinates_mb']:.0f} MB",
          f"  {JOB_FILE}    how to run the heavy analysis (per-atom diffusion, displacement distribution); "
          f"estimated {estimate_info['seconds']:.0f} s and {estimate_info['coordinates_mb']:.0f} MB of coordinates"),
        L(f"  {WORKER_FILE}   その本体 (numpy と scipy だけで動きます。ADIT は要りません)",
          f"  {WORKER_FILE}   the worker itself (numpy and scipy only; ADIT is not required)"),
        L(f"  実行すると {RESULT_FILE} ができます。そのあと adit-analyze <このディレクトリ> で図になります。",
          f"  Running it writes {RESULT_FILE}; then adit-analyze <this directory> turns it into figures."),
    ]
