
from __future__ import annotations

from dataclasses import dataclass

from adit.lang import L


@dataclass(frozen=True)
class Help:
    required: bool
    ja: str
    en: str

    def text(self) -> str:
        return L(self.ja, self.en)


R, O = True, False  # required / optional

HELP: dict[str, Help] = {
    "構造の作り方": Help(R, "計算する原子の並びをどこから作るか (土台)。プリセット (ASE の分子集)、SMILES (RDKit で 3 次元化)、ファイル、バルク結晶、表面スラブ、溶液・混合物、"
                        "2 次元材料・ナノチューブ、ナノ粒子、ポリマーのいずれか 1 つ。下の「組み立て手順」で、この土台に加工を重ねられます。",
                   "Where the atoms come from (the base): a preset (ASE molecule set), SMILES (3D via RDKit), a file, a bulk crystal, a surface slab, a solution / mixture, "
                   "a 2D material / nanotube, a nanoparticle or a polymer. The build steps below can then modify this base."),
    "プリセット": Help(R, "ASE に収録された分子 (G2 集など) を名前で選びます。座標は ASE の値です。", "A molecule from ASE's built-in set (G2 etc.); coordinates are ASE's."),
    "SMILES": Help(R, "分子を文字列で表す記法 (例 CCO = エタノール)。RDKit が配座を作り、力場 (MMFF) で粗く整えます。", "Line notation for molecules (e.g. CCO = ethanol). RDKit builds a conformer and relaxes it with MMFF."),
    "ファイル": Help(R, "ASE が読める構造ファイル (xyz, cif, POSCAR, gen など)。周期セルが書かれていれば周期系として扱います。", "Any structure file ASE can read (xyz, cif, POSCAR, gen, ...). A cell in the file makes it periodic."),
    "バルク": Help(R, "元素と結晶構造 (fcc, bcc, diamond など) から単位格子を作ります。格子定数 a を 0 にすると ASE の参照値を使います。", "Builds a unit cell from an element and a crystal structure (fcc, bcc, diamond, ...). a = 0 uses ASE's reference value."),
    "スラブ": Help(R, "表面の面指数 (fcc111 など) と元素からスラブを切り出します。層数と真空層の厚さを決めます。", "Cuts a slab from a surface (fcc111 etc.) of an element; choose the number of layers and the vacuum thickness."),
    "溶液・混合物": Help(R, "複数の分子・イオンを個数で指定し、立方体の箱に無作為に詰めます (周期系)。箱の大きさは密度 [g/cm³] か一辺 [Å] で決め、濃度 [mol/L] と全体電荷 (成分の電荷の和) を表示します。乱数の種を固定すれば同じ構造になります。",
                        "Packs several molecules / ions by count into a cubic periodic box. Box size from a density [g/cm³] or an edge [Å]; concentrations [mol/L] and the total charge (sum of component charges) are shown. A fixed seed reproduces the structure."),
    "2 次元材料・ナノチューブ": Help(R, "グラフェン型 (C₂、BN)、MX₂ 型 (MoS₂ など)、ナノリボン、ナノチューブを ASE で作ります。周期でない方向には真空を付け、3 方向とも周期のセルにします。",
                              "Builds a graphene-type sheet (C₂, BN), an MX₂ sheet (MoS₂ etc.), a nanoribbon or a nanotube with ASE. Vacuum is added along the non-periodic directions so the cell is periodic in all three."),
    "ナノ粒子": Help(R, "金属などのナノ粒子 (正二十面体、十面体、八面体、表面エネルギーから決める Wulff 形) を ASE で作ります。周期のない構造になるので、計算に周期セルが要るなら手順の「直方体のセル」か「溶媒和」を続けます。",
                    "Builds a nanoparticle (icosahedron, decahedron, octahedron, or a Wulff shape from surface energies) with ASE. The result is non-periodic; add a Box or Solvate step if the calculation needs a cell."),
    "ポリマー": Help(R, "繰り返し単位の SMILES (つなぐ位置に * を 2 つ) を重合度の数だけつないだ鎖 1 本を、RDKit で 3 次元化します。末端は H で終端します。鎖を何本も詰めることはしません。",
                    "Joins the repeat unit (a SMILES with two * connection points) into one chain of the given length and builds 3D coordinates with RDKit. The ends are capped with H. Packing many chains is not done."),
    "超格子の取り方": Help(O, "各軸の繰り返し (a, b, c をそれぞれ何倍にするか) か、3×3 の整数の変換行列 (斜めの取り方) のどちらか。", "Either repeats along each axis, or a 3×3 integer transformation matrix (for skewed supercells)."),
    "繰り返し (a × b × c)": Help(O, "格子ベクトル a, b, c の方向にそれぞれ何倍に並べるか。原子数は掛け算で増えます。", "How many times the cell is repeated along a, b and c; the atom count multiplies."),
    "変換行列": Help(O, "新しい格子 = 行列 × 元の格子。行列式が 1 以上 (右手系) の整数行列で、行列式の倍だけ原子が増えます。", "New cell = matrix × old cell. An integer matrix with determinant ≥ 1 (right-handed); the atom count grows by the determinant."),
    "ミラー指数 (h k l)": Help(R, "切る面の向き。いまのセルの格子ベクトルに対する指数です (基本セルか慣用セルかで意味が変わります)。", "Orientation of the cut plane, relative to the current cell vectors (the meaning differs between primitive and conventional cells)."),
    "層の数 (周期)": Help(O, "面に垂直な方向の繰り返し単位を何周期ぶん重ねるか。1 周期に原子面がいくつ入るかは面によります。", "How many repeat units are stacked normal to the surface; the number of atomic planes per repeat depends on the plane."),
    "真空 (片側) [Å]": Help(O, "板の上下それぞれに付ける真空の厚み (周期の像との隙間はこの 2 倍)。0 なら真空なし。", "Vacuum added on each side of the slab (the gap to the periodic image is twice this). 0 = no vacuum."),
    "終端 (最上面)": Help(O, "1 周期の中の原子面のうち、どれを最上面にするか。面の窓をずらすだけなので、組成は変わりません。", "Which atomic plane of one period becomes the top surface. It only shifts the window, so the composition is unchanged."),
    "軸": Help(O, "真空を付ける方向。スラブなら c (面に垂直な方向) です。", "Direction to add vacuum along; for a slab it is c (normal to the surface)."),
    "周期の像との隙間 [Å]": Help(O, "その方向で、構造の端と周期の像の端のあいだを何 Å 空けるか (いまの隙間は置き換えます)。", "Gap between the structure and its periodic image along this axis (replaces the current gap)."),
    "余白 [Å]": Help(O, "分子やナノ粒子の端から箱の面までの距離。周期の像どうしの距離はこの 2 倍になります。", "Distance from the outermost atoms to the box faces; periodic images end up twice this apart."),
    "倍数の上限": Help(O, "周期の構造を直交するセルに取り直すとき、元のセルの何倍まで大きくしてよいか。", "When re-cutting a periodic structure into an orthogonal cell, the largest allowed multiple of the original cell."),
    "元素 (条件)": Help(O, "選ぶ原子の元素 (空白かカンマで区切って複数可)。空欄なら元素で絞りません。", "Elements to select (several separated by spaces or commas). Empty = any element."),
    "z の範囲 [Å]": Help(O, "選ぶ原子の z 座標 (デカルト座標) の下限と上限。空欄ならその側は制限なし。条件はすべて「かつ」です。", "Lower and upper bounds on the Cartesian z of the selected atoms; empty = no bound on that side. All conditions must hold."),
    "選ぶ数": Help(R, "条件に合う原子から無作為に選ぶ数。個数か、合う原子に対する割合 (0〜1) のどちらか。", "How many of the matching atoms are picked at random: a count, or a fraction (0-1) of the matching atoms."),
    "乱数シード": Help(O, "無作為に選ぶ・置くときの乱数の種。同じ値なら同じ構造になります。", "Random seed for picking or placing; the same value gives the same structure."),
    "置き換え先の元素": Help(R, "選んだ原子をこの元素に置き換えます (ドープ、置換型の固溶体など)。電荷は自動では変えません。", "The selected atoms become this element (doping, substitutional alloys). The total charge is not changed automatically."),
    "分子": Help(R, "吸着させる分子 1 つ。プリセット、SMILES (Draw で描ける)、構造ファイルのどれか。", "The molecule to adsorb: a preset, a SMILES string (can be drawn with Draw) or a structure file."),
    "置き場所": Help(R, "分子を置く位置の決め方。席の名前 (ASE の面で作ったスラブだけ)、原子の真上、xy 座標のどれか。", "How the position is given: a site name (only for ASE surface slabs), above an atom, or an xy position."),
    "吸着サイトの名前": Help(R, "ASE の面関数の席 (ontop, bridge, fcc, hcp, hollow など)。面によって使える席が違います。", "A site of the ASE surface function (ontop, bridge, fcc, hcp, hollow, ...); available sites depend on the surface."),
    "原子の番号 (1 始まり)": Help(R, "この原子の真上に分子を置きます。番号は、この手順を実行する時点の並び (1 始まり) です。", "The molecule is placed above this atom, numbered (from 1) as the structure stands at this step."),
    "xy 座標 [Å]": Help(R, "分子を置く x, y (デカルト座標)。高さは構造のいちばん上の原子から測ります。", "Cartesian x and y of the molecule; the height is measured from the topmost atom."),
    "高さ [Å]": Help(O, "基準の原子 (席なら最上層、原子の真上ならその原子) から、分子の「下に向ける原子」までの高さ。", "Height from the reference atom (the top layer for a site, or the chosen atom) to the molecule's downward atom."),
    "下に向ける原子 (1 始まり)": Help(O, "分子のどの原子を面に向けるか (分子の中の番号、1 始まり)。分子の重心がこの原子の真上に来る向きに回します。", "Which atom of the molecule points at the surface (numbered within the molecule, from 1); the molecule is turned so its center sits right above it."),
    "厚みの決め方": Help(R, "溶液の帯の厚み。密度から (成分の総質量 ÷ 密度 ÷ 断面積) か、厚みを直接指定するか。厚みを直接決めると詰めすぎになりやすいので、はじめは密度からが確実です。",
                        "Thickness of the solution band: from a density (total mass ÷ density ÷ cross-section) or given directly. A directly given thickness easily overpacks, so starting from a density is safer."),
    "間隙 [Å]": Help(O, "板の上面と溶液の帯のあいだ (帯の上側にも同じだけ空けます) の隙間。", "Gap between the slab surface and the solution band (the same gap is left above the band)."),
    "真空 [Å] (0 なら両側が溶液)": Help(O, "溶液の上に置く真空の層の厚み。0 なら真空は無く、溶液は周期の像の板の下面にも接します (板の両側が溶液)。",
                                     "Thickness of a vacuum layer above the solution. 0 = no vacuum: the solution also touches the underside of the periodic image of the slab (solution on both sides)."),
    "濃度から個数": Help(O, "溶液の帯の体積と濃度 [mol/L] から、表で選んだ行 (イオンなど) の個数を出します。個数 = 濃度 × アボガドロ数 × 体積 (四捨五入)。値を決めるのは利用者です。",
                        "Sets the count of the selected row (such as an ion) from the band volume and a concentration [mol/L]: count = concentration × Avogadro × volume (rounded). The value is yours to choose."),
    "溶質の周りの余白 [Å]": Help(O, "周期のない溶質 (分子・ナノ粒子) を置く直方体の箱の、溶質の端から面までの距離。周期の構造なら今のセルのまま。", "For a non-periodic solute, distance from its outermost atoms to the faces of the box. A periodic structure keeps its cell."),
    "密度 [g/cm³]": Help(O, "個数を「自動」にした成分を、箱全体 (溶質を含む) がこの密度になるまで入れます。", "The component set to auto is added until the whole box (solute included) reaches this density."),
    "下から数えた層": Help(O, "z の小さい方から数えた原子面の数 (z の差 0.5 Å より大きいところで面を分けます)。0 なら層では選びません。", "Number of atomic planes counted from the bottom (planes are separated where z differs by more than 0.5 Å). 0 = not used."),
    "周期セルに入れる": Help(O, "分子を一辺 L の立方体の周期セルに置きます。VASP と pw.x は周期セルが無いと動きません。L は分子どうしの像が触れない大きさにします。",
                          "Puts the molecule in a cubic periodic cell of edge L. VASP and pw.x need a cell; L must keep periodic images apart."),
    "固定原子": Help(O, "構造最適化や MD で動かさない原子。1 始まりの番号 (例 1-4,7)。7:xy のように書くとその軸だけ止めます。スラブの下層を固定するときなどに使います。",
                    "Atoms kept fixed during optimization or MD, 1-based (e.g. 1-4,7). 7:xy freezes only those axes. Typical for the bottom layers of a slab."),
    "全電荷": Help(O, "系全体の電荷 (電子を減らすと正)。電子数を変えるので、多重度と偶奇が合っている必要があります。", "Net charge of the system (positive = fewer electrons). It changes the electron count, so it must be consistent with the multiplicity."),
    "スピン多重度": Help(O, "2S+1。不対電子の数 + 1 です (閉殻なら 1、ラジカルなら 2、三重項なら 3)。電子数の偶奇と合わないと生成できません。",
                    "2S+1: number of unpaired electrons + 1 (1 closed shell, 2 radical, 3 triplet). Must match the parity of the electron count."),
    "種類": Help(R, "何を計算するか。一点計算 (エネルギーと力)、構造最適化、分子動力学、振動解析、バンド計算 (周期系のみ)。", "What to compute: single point (energy and forces), geometry optimization, molecular dynamics, vibrations, or band structure (periodic only)."),
    "最適化アルゴリズム": Help(O, "構造を安定点へ動かす方法。Rational は DFTB+ の既定。LBFGS は準ニュートン法、FIRE は速度緩和法、SteepestDescent は最急降下法。", "How atoms are moved toward a minimum. Rational is the DFTB+ default; LBFGS quasi-Newton; FIRE velocity damping; SteepestDescent."),
    "最大ステップ数 (MaxSteps)": Help(O, "構造最適化の最大ステップ数。ここまでに収束しなければ止まります。", "Maximum number of optimization steps; stops here if not converged."),
    "力の収束判定 [eV/Å]": Help(O, "全原子の力がこの値より小さくなったら収束とみなします。小さいほど厳密で、ステップ数が増えます。"
                                  "既定の 0.00514221 は、DFTB+ の既定値 1e-4 Hartree/Bohr を eV/Å に換算した値です (半端なのは換算のため)。",
                                  "Converged when all forces fall below this value. Smaller is stricter and needs more steps. "
                                  "The default 0.00514221 is DFTB+'s default 1e-4 Hartree/Bohr converted to eV/Å (hence the odd number)."),
    "セルの緩和 (周期系)": Help(O, "構造最適化で格子ベクトルも動かすか。形と体積 / 体積だけ / 動かさない。周期系だけの項目です。", "Whether the cell is relaxed too: shape and volume, volume only, or fixed. Periodic systems only."),
    "アンサンブル": Help(O, "MD で何を一定に保つか。NVE (エネルギー一定)、NVT (温度一定、熱浴あり)、NPT (温度と圧力一定、周期系のみ)。", "What MD keeps constant: NVE (energy), NVT (temperature, thermostat), NPT (temperature and pressure, periodic only)."),
    "熱浴": Help(O, "温度を目標値に保つ方法。Berendsen は速度のスケーリング、Andersen は確率的な速度の置き換え、Nosé-Hoover は拡張系、Langevin は摩擦と乱雑力、CSVR は正準分布に従う速度再スケール。コードにより使えるものが違います。",
                "How the temperature is held: Berendsen (velocity scaling), Andersen (random velocity reassignment), Nosé-Hoover (extended system), Langevin (friction + noise), CSVR (canonical velocity rescaling). Availability depends on the code."),
    "温度 [K]": Help(O, "MD の目標温度。NVE では初速を与えるための温度です。", "Target temperature of the MD; in NVE it only sets the initial velocities."),
    "時間刻み [fs]": Help(O, "運動方程式を積分する刻み。水素を含む系では 0.5〜1 fs 程度が普通です (値の判断は利用者が行います)。", "Integration time step. Systems with hydrogen usually use about 0.5-1 fs (the choice is yours)."),
    "MD ステップ数": Help(O, "積分する回数。時間刻み × ステップ数 が模擬する時間です。", "Number of steps; step × time step is the simulated time."),
    "軌跡の出力間隔 [ステップ]": Help(O, "何ステップごとに座標を書き出すか。解析 (RDF、MSD) はこの軌跡を読みます。", "How often coordinates are written; the analysis (RDF, MSD) reads this trajectory."),
    "熱浴の緩和時間 [fs]": Help(O, "熱浴が温度を目標へ戻す速さ。各コードの結合パラメータ (Berendsen の τ、Andersen の確率、Nosé-Hoover の周波数、Langevin の摩擦) へ機械的に換算します。",
                       "How fast the thermostat pulls the temperature back. Converted mechanically to each code's coupling parameter (Berendsen τ, Andersen probability, Nosé-Hoover frequency, Langevin friction)."),
    "圧力 [bar] (NPT)": Help(O, "NPT の目標圧力。1 bar ≈ 大気圧。", "Target pressure of NPT; 1 bar is about atmospheric."),
    "圧力浴の緩和時間 [fs] (NPT)": Help(O, "圧力浴 (バロスタット) がセルの体積を目標圧力へ戻す速さ。", "How fast the barostat adjusts the cell volume toward the target pressure."),
    "k 点の経路 (バンド)": Help(O, "バンド図を描く逆格子空間の道筋。空なら格子の対称性から決まる標準の経路 (ASE)。GXWKGLUWLK,UX のように高対称点の記号で書きます。", "Path in reciprocal space for the band plot. Empty = the standard path of the lattice (ASE). Written with high-symmetry labels like GXWKGLUWLK,UX."),
    "経路上の k 点数": Help(O, "経路全体を何点で刻むか。多いほど滑らかな図になります。", "Number of k-points along the whole path; more gives a smoother plot."),
    "空のバンド数 (pw.x)": Help(O, "価電子帯に加えて計算する空のバンドの数 (pw.x の nbnd に使います)。伝導帯を見たいときに増やします。", "Empty bands computed in addition to the valence bands (pw.x nbnd). Increase to see the conduction bands."),
    "サンプリング方法": Help(R, "結晶の中の電子の波を、何通りの波の向き・長さ (k 点) で代表させるか。セルが小さいほど多くの k 点が要り、少ないとエネルギーがずれます。"
                            "Γ 点のみ (1 点。数百原子の大きなセル向け)、分割数を指定、密度から自動で決める、から選びます。専門的には「ブリルアン領域の刻み方」です。",
                            "How many wave vectors (k-points) represent the electrons in the crystal. Smaller cells need more k-points; too few shifts the energy. "
                            "Γ only (one point; large cells of hundreds of atoms), an explicit mesh, or an automatic density. Technically: Brillouin-zone sampling."),
    "メッシュ (n1 n2 n3)": Help(R, "セルの 3 つの辺の方向それぞれに、k 点を何点並べるか。短い辺の方向ほど多く要ります (例: Si の基本セルで 8 8 8 程度から試し、値を増やしてエネルギーが変わらなくなる所を探すのが普通)。"
                                "シフトは 0 (Γ を含む) か 0.5 (Monkhorst-Pack 型)。",
                                "How many k-points along each of the three cell directions; short directions need more (e.g. start around 8 8 8 for the Si primitive cell and increase until the energy stops changing). "
                                "Shift 0 includes Γ, 0.5 is Monkhorst-Pack-like."),
    "k 点密度 [点/Å⁻¹]": Help(R, "セルの大きさに合わせて分割数を自動で決めるときの細かさ (逆格子の長さ 1/Å あたりの点数)。セルを変えても同じ細かさで比べたいときに便利です。",
                             "Fineness used to choose the mesh automatically from the cell (points per 1/Å of reciprocal length). Handy for comparing cells at the same fineness."),
    "計算コード": Help(R, "入力を作る計算プログラム。DFTB+ (密度汎関数強束縛)、VASP (平面波 DFT)、xtb (半経験的 GFN-xTB)、Quantum ESPRESSO pw.x (平面波 DFT)、ORCA (分子の量子化学)、"
                        "CP2K (ガウス基底と平面波を併用する DFT)、LAMMPS と GROMACS (力場を使う古典分子動力学)。",
                   "The program to generate input for: DFTB+ (tight binding), VASP (plane-wave DFT), xtb (GFN-xTB), Quantum ESPRESSO pw.x (plane-wave DFT), ORCA (molecular quantum chemistry), "
                   "CP2K (DFT with Gaussian and plane-wave bases), LAMMPS and GROMACS (classical MD with force fields)."),
    # ---- CP2K ----
    "汎関数": Help(R, "交換相関汎関数の名前 (CP2K の XC_FUNCTIONAL。PBE、BLYP、PBE0 など)。擬ポテンシャルは同じ汎関数で作られたものを選びます (GTH-PBE なら PBE)。",
                  "Name of the exchange-correlation functional (CP2K XC_FUNCTIONAL: PBE, BLYP, PBE0, ...). Pick pseudopotentials made for the same functional (GTH-PBE for PBE)."),
    "基底関数のファイル": Help(O, "基底関数の一覧のファイル。CP2K の data ディレクトリの中の名前 (BASIS_MOLOPT など) か絶対パス。",
                            "The basis-set file: a name in the CP2K data directory (BASIS_MOLOPT etc.) or an absolute path."),
    "擬ポテンシャルのファイル": Help(O, "擬ポテンシャル (内殻電子の効果をまとめたもの) の一覧のファイル。data ディレクトリの中の名前 (GTH_POTENTIALS など) か絶対パス。",
                               "The pseudopotential file (pseudopotentials stand in for the core electrons): a name in the data directory (GTH_POTENTIALS etc.) or an absolute path."),
    "元素ごとの基底と擬ポテンシャル": Help(O, "元素ごとに使う基底関数 (左) と擬ポテンシャル (右) の名前。候補はファイルから読んだものです。ファイルにその元素の候補が 1 つだけなら、空欄のままでそれを使います。"
                                   "基底の名前の -q6 のような末尾は価電子の数で、擬ポテンシャルの価電子の数と合っている必要があります。",
                                   "Basis set (left) and pseudopotential (right) per element; the choices are read from the files. If the file has only one entry for the element, "
                                   "leaving it empty uses that one. A suffix like -q6 is the number of valence electrons and must match the pseudopotential."),
    "分散補正": Help(O, "ファンデルワールス力の補正。CP2K の D3 と D3(BJ) は Grimme の方法で、係数は CP2K の dftd3.dat から汎関数の名前で引かれます。"
                    "機械学習ポテンシャルでは mace_mp の D3 (dispersion) です。",
                    "Van der Waals correction. In CP2K, D3 and D3(BJ) are Grimme's methods and the parameters come from dftd3.dat by the functional name; "
                    "for a machine-learning potential it is the D3 option (dispersion) of mace_mp."),
    "カットオフ [Ry]": Help(R, "電子密度を表す実空間の格子の細かさ (MGRID の CUTOFF)。大きいほど精密で遅くなります。CP2K のマニュアルの「CUTOFF と REL_CUTOFF の収束」の手順で、値を上げてエネルギーが変わらなくなる所を探して決めます。",
                             "Fineness of the real-space grid for the density (MGRID CUTOFF); larger is more precise and slower. The CP2K manual page on converging CUTOFF and REL_CUTOFF shows how to raise it until the energy stops changing."),
    "相対カットオフ [Ry]": Help(R, "ガウス関数をどの細かさの格子に割り当てるかの基準 (MGRID の REL_CUTOFF)。カットオフと同じ手順で決めます。", "Decides which grid level each Gaussian is mapped to (MGRID REL_CUTOFF); chosen by the same procedure as the cutoff."),
    "SCF の収束の閾値 (EPS_SCF)": Help(O, "SCF の反復を止める基準 (密度の変化)。既定の 1e-5 は CP2K の既定値です。小さいほど厳密です。", "SCF convergence threshold (change of the density). The default 1e-5 is CP2K's own default; smaller is stricter."),
    "SCF の反復の上限 (MAX_SCF)": Help(O, "SCF の反復の上限。既定の 50 は CP2K の既定値です。", "Maximum SCF iterations; the default 50 is CP2K's own default."),
    "スピン分極": Help(O, "α スピンと β スピンの電子を別々に扱う (UKS)。スピン多重度が 1 でないときは必須です。", "Treat α and β electrons separately (UKS). Required when the spin multiplicity is not 1."),
    "ポアソン方程式の解き方": Help(O, "周期でない方向があるときの静電ポテンシャルの求め方 (MT、WAVELET、ANALYTIC、MULTIPOLE)。分子や表面のように周期でない方向があるときは必須、3 方向とも周期なら使いません。"
                              "MT は箱を分子の約 2 倍の大きさにする前提です (CP2K のマニュアル)。",
                              "How the electrostatics are solved when some direction is not periodic (MT, WAVELET, ANALYTIC, MULTIPOLE). Required for molecules and surfaces, unused when all three directions are periodic. "
                              "MT assumes a box about twice the size of the molecule (CP2K manual)."),
    "分子の箱の一辺 [Å]": Help(O, "周期でない分子の構造に箱が無いときの、立方体の箱の一辺。CP2K は箱の中で計算するので、そのときは必須です。分子は箱の中心に置かれます。",
                           "Edge of the cubic box when a non-periodic molecule has no cell. CP2K always computes inside a box, so it is then required; the molecule is centered."),
    "軌道変換法 (OT)": Help(O, "CP2K の SCF で軌道変換法 (&OT) を使うかどうか。選んだときだけ &OT 節を書きます。", "Whether to use CP2K's orbital-transformation method (&OT) for SCF; the &OT section is written only when selected."),
    "OT MINIMIZER": Help(O, "&OT の MINIMIZER。値は利用者が CP2K の文書に基づいて選びます。", "MINIMIZER in &OT; choose it according to the CP2K documentation."),
    "OT PRECONDITIONER": Help(O, "&OT の PRECONDITIONER。値は利用者が CP2K の文書に基づいて選びます。", "PRECONDITIONER in &OT; choose it according to the CP2K documentation."),
    "OT の追加行": Help(O, "画面にない &OT の項目を、1 行に 1 つ書きます。", "Additional &OT settings, one per line."),
    "SURFACE_DIPOLE_CORRECTION": Help(O, "CP2K の表面双極子補正を使うかどうか。利用者が選んだときだけ書きます。", "Whether to enable CP2K's surface dipole correction; written only when selected."),
    "SURF_DIP_DIR": Help(O, "表面双極子補正を適用する方向。", "Direction in which the surface dipole correction is applied."),
    "追加の行 (節ごと)": Help(O, "画面に無い CP2K の設定の逃げ道。[FORCE_EVAL/DFT/SCF] のような見出しの次の行に書いた行を、その節の末尾にそのまま足します。",
                          "Escape hatch for CP2K settings not in the form: lines under a header such as [FORCE_EVAL/DFT/SCF] are appended to the end of that section as is."),
    # ---- LAMMPS ----
    "単位系 (units)": Help(R, "力場のファイルが前提とする単位系。metal (eV、Å、ps、bar) か real (kcal/mol、Å、fs、atm)。EAM は多くが metal、ReaxFF や分子の力場は多くが real です。ファイルの説明で確かめます。",
                         "The unit system the force field assumes: metal (eV, Å, ps, bar) or real (kcal/mol, Å, fs, atm). Most EAM files use metal; ReaxFF and molecular force fields mostly real. Check the file."),
    "原子の形式 (atom_style)": Help(O, "data ファイルの Atoms の節の形。構造から ADIT が data を書くときは atomic (電荷なし) か charge (電荷あり)。外部の data ファイルならその形 (full など)。",
                                 "Format of the Atoms section. atomic (no charges) or charge when ADIT writes the data file from the structure; for an external data file, its own format (full etc.)."),
    "data ファイル": Help(O, "外部で作った LAMMPS の data ファイル (結合・角・電荷つき。moltemplate、fftool などで作ったもの)。空欄なら構造から data.lammps を書きます。使うときは構造の群にも同じ系を読み込みます。",
                        "An external LAMMPS data file (with bonds, angles and charges, e.g. from moltemplate or fftool). Empty = data.lammps is written from the structure. Load the same system as the structure too."),
    "型番号の元素": Help(O, "原子の型番号 1, 2, … が、それぞれどの元素か (空白区切り)。外部の data ファイルなら必須で、軌跡に元素名を書くのに使います。空欄なら構造の元素の出現順です。",
                       "Element of each atom type 1, 2, … (space separated). Required for an external data file; used to write element names into the trajectory. Empty = elements in the order they appear in the structure."),
    "pair_style": Help(R, "相互作用の種類の行 (例 eam、eam/alloy、reaxff NULL、mace no_domain_decomposition)。そのまま in.lammps に書きます。", "The pair_style line (e.g. eam, eam/alloy, reaxff NULL, mace no_domain_decomposition), written to in.lammps as is."),
    "pair_coeff": Help(R, "相互作用の係数の行 (例 * * Cu_u3.eam)。構造から data を書くときは必須です。外部の data ファイルに Pair Coeffs の節があれば省けます。ファイルは名前だけで書き、「写すファイル」に入れます。",
                       "The pair_coeff lines (e.g. * * Cu_u3.eam). Required when the data file is written from the structure; may be omitted if an external data file has a Pair Coeffs section. Refer to files by name only and add them to the files to copy."),
    "写すファイル": Help(O, "生成したディレクトリへ写すファイル (EAM のファイル、ReaxFF の ffield、機械学習ポテンシャルのモデル)。1 行に 1 つ。", "Files copied into the output directory (EAM files, ReaxFF ffield, machine-learning models), one per line."),
    "read_data の前の行": Help(O, "read_data の前に置く行 (bond_style、angle_style、special_bonds など、分子の力場で要るもの)。", "Lines placed before read_data (bond_style, angle_style, special_bonds, ... as molecular force fields need)."),
    "pair_coeff の後の行": Help(O, "pair_coeff の後に置く行 (kspace_style、fix qeq/reaxff、neigh_modify など)。", "Lines placed after pair_coeff (kspace_style, fix qeq/reaxff, neigh_modify, ...)."),
    "乱数の種": Help(O, "乱数の種。同じ値なら同じ結果になります。LAMMPS と機械学習ポテンシャルでは初速と確率的な熱浴 (Langevin、CSVR)、"
                    "配座の候補では RDKit の ETKDG に使います (LAMMPS では 1 以上の整数)。",
                    "Random seed; the same value reproduces the same result. It is used for the initial velocities and stochastic thermostats "
                    "(Langevin, CSVR) in LAMMPS and machine-learning potentials, and for RDKit ETKDG in the conformer search (LAMMPS needs a positive integer)."),
    # ---- GROMACS ----
    "トポロジー (.top)": Help(R, "分子の種類と数、力場を書いたトポロジー (CHARMM-GUI、acpype、pdb2gmx などで作ったもの)。相対の #include はこのファイルの場所から探して一緒に写します。",
                           "The topology (molecule types and counts, force field) made with CHARMM-GUI, acpype, pdb2gmx, etc. Relative #include files are looked up next to it and copied along."),
    "構造のファイル (.gro / .pdb)": Help(R, "計算に使う構造。GROMACS ではこのファイルが正本です。構造の群にも同じファイルを読み込むと、原子数の確認と 3D 表示に使われます。",
                                    "The structure used by the run; for GROMACS this file is authoritative. Loading the same file in the structure group lets ADIT check the atom count and show it in 3D."),
    "静電相互作用 (coulombtype)": Help(O, "静電相互作用の扱い。Cut-off (GROMACS の既定)、PME (長距離を逆空間で和をとる)、Reaction-Field。", "Treatment of electrostatics: Cut-off (the GROMACS default), PME (long range summed in reciprocal space), or Reaction-Field."),
    "カットオフ [nm]": Help(O, "静電 (rcoulomb) とファンデルワールス (rvdw) の相互作用を打ち切る距離。既定の 1 nm は GROMACS の既定値です。力場の文書に指定があればそれに合わせます。",
                            "Cut-off distances for electrostatics (rcoulomb) and van der Waals (rvdw). The default 1 nm is GROMACS's own default; follow the force field's documentation if it specifies them."),
    "拘束 (constraints)": Help(O, "結合長を固定する範囲。none (GROMACS の既定)、h-bonds (H を含む結合)、all-bonds など。", "Which bond lengths are constrained: none (the GROMACS default), h-bonds (bonds to H), all-bonds, ..."),
    "圧力浴 (pcoupl)": Help(O, "NPT で圧力を保つ方法。C-rescale か Parrinello-Rahman。NPT のときは必須です (GROMACS に既定がありません)。Parrinello-Rahman は前の段階の .cpt から続けるときに使います。",
                        "How pressure is held in NPT: C-rescale or Parrinello-Rahman. Required for NPT (GROMACS has no default). Parrinello-Rahman is for continuing from a previous stage's .cpt."),
    "等温圧縮率 [1/bar]": Help(O, "系の等温圧縮率。圧力浴が体積を動かす大きさを決めます。NPT のときは必須です。GROMACS のマニュアルの水の例では 4.5e-5 です。",
                           "Isothermal compressibility of the system; scales how the barostat changes the volume. Required for NPT. The GROMACS manual uses 4.5e-5 for water."),
    "define": Help(O, "トポロジーの #ifdef を有効にする指定 (例 -DPOSRES で位置の拘束)。", "Enables #ifdef blocks of the topology (e.g. -DPOSRES for position restraints)."),
    "前の段階の .cpt": Help(O, "前の段階 (NVT → NPT → 本計算) の gmx mdrun が書いた .cpt。あれば続きから計算し、速度を作り直しません。", "The .cpt written by the previous stage (NVT → NPT → production). If given, the run continues from it without new velocities."),
    "初速の乱数の種 (gen-seed)": Help(O, "初速を作るときの乱数の種。ADIT が置く 12345 は spec.json に残るため、同じ初速を再現できます。",
                                      "Random seed for generating initial velocities. ADIT supplies 12345 and records it in spec.json so the same initial velocities can be reproduced."),
    "追加の mdp": Help(O, "画面に無い mdp の項目を「名前 = 値」の行で書きます。同じ名前の項目は上書きします。", "mdp options not in the form, as name = value lines; they override items of the same name."),
    # ---- DFTB+ ----
    "Slater-Koster パラメータ": Help(R, "DFTB+ のパラメータ (元素ペアごとの skf ファイルの組)。対応元素はセットで決まります。sk_root の下のディレクトリから選びます。", "The DFTB+ parameter set (skf files per element pair); it decides which elements are available. Chosen from directories under sk_root."),
    "SCC (自己無撞着電荷)": Help(O, "原子電荷を自己無撞着に決めるか (DFTB2 以上)。外すと非自己無撞着の DFTB1 になります。", "Whether atomic charges are determined self-consistently (DFTB2+). Unchecked = non-self-consistent DFTB1."),
    "SCC の収束判定 (SccTolerance)": Help(O, "SCC 反復の収束判定 (電荷の変化がこの値以下で収束)。小さいほど厳密です。", "Convergence threshold of the SCC loop (change in charges). Smaller is stricter."),
    "SCC の反復上限 (MaxSccIterations)": Help(O, "SCC 反復の上限。ここまでに収束しなければ止まります。", "Maximum SCC iterations."),
    "DFTB3 (ThirdOrderFull)": Help(O, "3 次の項を入れる DFTB3。セットの README に Hubbard 微分値と H-X 減衰の指数が要ります。", "Third-order DFTB3; needs Hubbard derivatives and the H-X damping exponent from the set's README."),
    "分散力補正": Help(O, "ファンデルワールス力の補正。dftd3 は Grimme の D3 (BJ 減衰)、lennard-jones は UFF の LJ ポテンシャル。", "Van der Waals correction: dftd3 = Grimme's D3 (BJ damping), lennard-jones = UFF LJ potential."),
    "DFT-D3 係数 (BJ)": Help(O, "D3 (BJ 減衰) の 4 係数 s6, s8, a1, a2。パーサのバージョン 7 以降は既定値が無いので、セットの文書 (skf/README など) か文献の値を入れます。"
                            "4 つとも 0 のままでは分散力が入りません。分散力補正が none のときは使いません。",
                            "The four D3(BJ) parameters s6, s8, a1, a2. No defaults since parser version 7; take them from the set's documentation or the literature. "
                            "With all four at 0 no dispersion is added. Unused when dispersion is none."),
    "電子温度 [K]": Help(O, "電子の占有をフェルミ分布で広げる温度。0 なら整数占有。金属や収束しにくい系で使われます。", "Electronic temperature for Fermi smearing of occupations; 0 = integer occupations. Used for metals or hard-to-converge systems."),
    # ---- VASP ----
    "POTCAR のセット": Help(R, "POTCAR ライブラリの中のディレクトリ名 (potpaw_PBE など)。汎関数の系統を決めます。", "Directory name inside the POTCAR library (e.g. potpaw_PBE); selects the functional family."),
    "元素ごとの POTCAR 名": Help(O, "元素ごとに使う POTCAR の名前 (Li_sv など。_sv は半内殻を価電子に含む)。空なら元素名そのもの。", "POTCAR name per element (e.g. Li_sv; _sv treats semi-core states as valence). Empty = the element name."),
    "実行ファイルの種類": Help(O, "vasp_std (一般)、vasp_gam (Γ 点のみ。速い)、vasp_ncl (非共線スピン)。", "vasp_std (general), vasp_gam (Γ only, faster), vasp_ncl (non-collinear spin)."),
    "IBRION (構造最適化の方法)": Help(O, "イオンの動かし方。1: RMM-DIIS (準ニュートン、安定点の近く)、2: 共役勾配、3: 減衰 MD。一点計算では -1 を書きます。", "How ions move: 1 RMM-DIIS (quasi-Newton, near a minimum), 2 conjugate gradient, 3 damped MD. Single points write -1."),
    "ENCUT [eV] (0 = 指定しない)": Help(O, "平面波の運動エネルギーの上限。大きいほど基底が大きく精度が上がり、時間もかかります。0 なら POTCAR の ENMAX に任せます。", "Plane-wave cutoff energy; larger = bigger basis, higher accuracy, more time. 0 leaves it to ENMAX of the POTCAR."),
    "PREC": Help(O, "精度の総合設定 (FFT 格子や実空間投影の細かさ)。Normal / Accurate など。", "Overall precision preset (FFT grid, real-space projection)."),
    "ALGO": Help(O, "電子状態の最適化アルゴリズム。Normal (Davidson)、Fast、VeryFast、All、Damped。", "Electronic minimization algorithm: Normal (Davidson), Fast, VeryFast, All, Damped."),
    "EDIFF [eV]": Help(O, "電子ステップの収束判定 (全エネルギーの変化)。", "Convergence threshold of the electronic loop (total energy change)."),
    "NELM": Help(O, "電子ステップの上限。", "Maximum electronic steps."),
    "ISMEAR": Help(O, "占有のぼかし方。0: ガウス、-5: 四面体法 (Blöchl 補正)、1〜: Methfessel-Paxton。", "Smearing method: 0 Gaussian, -5 tetrahedron (Blöchl), 1+ Methfessel-Paxton."),
    "SIGMA [eV]": Help(O, "ぼかしの幅。ISMEAR に応じた意味を持ちます。", "Smearing width, meaning depends on ISMEAR."),
    "ISPIN": Help(O, "1: スピンなし、2: スピン分極。多重度が 1 でないときは 2 が要ります。", "1 non-spin-polarized, 2 spin-polarized. Needed for multiplicity ≠ 1."),
    "MAGMOM": Help(O, "各原子の初期磁気モーメント (μB)。原子数と同じ個数を空白区切りで。空なら書きません。", "Initial magnetic moment per atom (μB), space-separated, one per atom. Empty = not written."),
    "IVDW": Help(O, "ファンデルワールス補正。11: D3、12: D3(BJ)、20: Tkatchenko-Scheffler。", "Van der Waals correction: 11 D3, 12 D3(BJ), 20 Tkatchenko-Scheffler."),
    "LREAL": Help(O, "投影演算子を実空間で評価するか。Auto は大きなセルで速く、.FALSE. は逆空間で精密。", "Real-space projection: Auto is faster for large cells, .FALSE. is more precise (reciprocal space)."),
    "追加の INCAR 設定": Help(O, "画面に無い INCAR のキーを「KEY = value」の行で書きます。そのまま INCAR に書かれます。", "INCAR keys not in the form, as KEY = value lines, written as is."),
    # ---- xtb ----
    "計算手法 (--gfn)": Help(O, "GFN2-xTB (既定)、GFN1、GFN0、GFN-FF (力場)。数字が大きいほど新しい方法です。", "GFN2-xTB (default), GFN1, GFN0, or GFN-FF (force field)."),
    "精度 (--acc)": Help(O, "数値精度の目安。小さいほど厳密 (積分格子や収束判定が細かくなります)。", "Accuracy level; smaller is stricter (grids and thresholds)."),
    "電子温度 [K] (--etemp)": Help(O, "電子占有のフェルミ温度。xtb の既定は 300 K。", "Fermi temperature of the electronic occupations; xtb default 300 K."),
    "SCC の最大反復回数": Help(O, "SCC 反復の上限。", "Maximum SCC iterations."),
    "最適化の収束レベル (--opt)": Help(O, "構造最適化の収束の厳しさ (crude〜extreme)。", "Tightness of the optimization convergence (crude to extreme)."),
    # ---- Quantum ESPRESSO ----
    "擬ポテンシャルのセット": Help(R, "pseudo_root の下のディレクトリ名 (pslibrary、SSSP_efficiency など)。中の UPF を使います。", "Directory under pseudo_root (pslibrary, SSSP_efficiency, ...); its UPF files are used."),
    "元素ごとの UPF ファイル": Help(O, "元素ごとに使う UPF ファイル。ライブラリにその元素のファイルが 1 つだけならそれを使います。複数あれば選びます。", "UPF file per element; used automatically if the set has exactly one for the element, otherwise choose."),
    "ecutwfc [Ry]": Help(R, "波動関数の平面波カットオフ。UPF の推奨値 (ファイル頭の Suggested minimum cutoff) を目安にします。0 では生成できません。", "Plane-wave cutoff of the wavefunctions. See the suggested minimum cutoff in the UPF header. 0 cannot be generated."),
    "ecutrho [Ry] (0 = 指定しない)": Help(O, "電荷密度のカットオフ。0 なら pw.x の既定 (4 × ecutwfc)。ウルトラソフト / PAW では 8〜12 倍にすることが多いです。", "Charge-density cutoff; 0 = pw.x default (4 × ecutwfc). Ultrasoft / PAW often use 8-12 ×."),
    "conv_thr [Ry]": Help(O, "SCF の収束判定 (エネルギーの推定誤差)。", "SCF convergence threshold (estimated energy error)."),
    "electron_maxstep": Help(O, "SCF 反復の上限。", "Maximum SCF iterations."),
    "mixing_beta": Help(O, "電荷密度の混合比。小さいほど安定で遅い。", "Charge-density mixing factor; smaller is more stable but slower."),
    "occupations": Help(O, "占有の扱い。fixed (絶縁体)、smearing (金属。degauss が要る)、tetrahedra (DOS 向け)。", "Occupations: fixed (insulators), smearing (metals, needs degauss), tetrahedra (for DOS)."),
    "smearing": Help(O, "smearing のときのぼかし関数。", "Smearing function when occupations = smearing."),
    "degauss [Ry]": Help(O, "ぼかしの幅。smearing のときは 0 より大きい値が要ります。", "Smearing width; must be > 0 with smearing."),
    "nspin": Help(O, "1: スピンなし、2: 共線スピン分極。多重度が 1 でないときは 2 が要ります。", "1 non-spin-polarized, 2 collinear spin-polarized. Needed for multiplicity ≠ 1."),
    "input_dft": Help(O, "交換相関汎関数を UPF のものから変えるとき (例 vdw-df2)。空なら UPF に従います。", "Override the XC functional of the UPF (e.g. vdw-df2). Empty follows the UPF."),
    "追加の変数 (名前空間.変数 = 値)": Help(O, "画面に無い pw.x の変数を「名前空間.変数 = 値」の行で (例 system.nbnd = 20)。", "pw.x variables not in the form, as namelist.variable = value lines (e.g. system.nbnd = 20)."),
    # ---- ORCA ----
    "計算手法 (! 行)": Help(R, "! 行の手法キーワード (HF、PBE、B3LYP、MP2、DLPNO-CCSD(T) など)。", "Method keyword of the ! line (HF, PBE, B3LYP, MP2, DLPNO-CCSD(T), ...)."),
    "基底関数": Help(R, "基底関数系のキーワード (def2-SVP、def2-TZVP、cc-pVTZ など)。大きいほど精密で遅い。", "Basis set keyword (def2-SVP, def2-TZVP, cc-pVTZ, ...); larger is more precise and slower."),
    "SCF の収束判定": Help(O, "SCF の収束の厳しさ (LooseSCF / NormalSCF / TightSCF)。", "SCF convergence tightness (LooseSCF / NormalSCF / TightSCF)."),
    "SCF の最大反復回数": Help(O, "SCF 反復の上限。", "Maximum SCF iterations."),
    "%maxcore [MB] (0 = 指定しない)": Help(O, "1 コアあたりに使ってよいメモリ (MB)。相関計算 (MP2、CC) で要ります。", "Memory per core (MB); needed for correlated methods (MP2, CC)."),
    "追加のキーワード (! 行)": Help(O, "! 行に足すキーワード (例 D3BJ RIJCOSX)。", "Extra keywords for the ! line (e.g. D3BJ RIJCOSX)."),
    "追加の %ブロック": Help(O, "%ブロックをそのまま足します (複数行可)。", "Extra %blocks, written as is."),
    "溶媒の模型 (--alpb / --gbsa)": Help(O, "連続誘電体で溶媒の効果を入れる模型 (xtb の --alpb / --gbsa)。「なし」なら気相です。GFN0-xTB では使えません。",
                                     "Implicit-solvent model (xtb --alpb / --gbsa); None = gas phase. Not available with GFN0-xTB."),
    "溶媒の模型 (CPCM / SMD)": Help(O, "連続誘電体で溶媒の効果を入れる模型 (! CPCM(溶媒) / ! SMD(溶媒))。「なし」なら気相です。",
                                "Implicit-solvent model (! CPCM(solvent) / ! SMD(solvent)); None = gas phase."),
    "溶媒": Help(O, "溶媒の名前。候補は、選んだ模型と計算手法でその計算コードが受け付ける名前です (xtb の文書、ORCA 6.1 マニュアルの溶媒の表)。模型を選んだら必須です。ADIT は溶媒を選びません。",
                "Solvent name. The choices are the names the code accepts for the chosen model and method (xtb documentation, solvent table of the ORCA 6.1 manual). "
                "Required once a model is chosen; ADIT does not pick one."),
    "溶媒のパラメータファイル (GBSA)": Help(O, "DFTB+ の Solvation = GeneralisedBorn に渡す GBSA のパラメータファイル (param_gbsa_<溶媒>.txt の形)。空なら溶媒なし。分子 (非周期) だけで使えます。係数はファイルから読むだけです。",
                                     "GBSA parameter file for DFTB+ Solvation = GeneralisedBorn (a file like param_gbsa_<solvent>.txt); empty = no solvent. "
                                     "Molecules (non-periodic) only; the coefficients are read from the file."),
    "溶媒の比誘電率 (SCCS)": Help(O, "CP2K の SCCS (自己無撞着な連続溶媒) の比誘電率 (RELATIVE_PERMITTIVITY)。0 なら溶媒なし。CP2K は溶媒の名前の表を持たないので、数値で与えます。",
                              "Relative permittivity for CP2K SCCS (self-consistent continuum solvation, RELATIVE_PERMITTIVITY); 0 = no solvent. "
                              "CP2K has no table of solvent names, so it is given as a number."),
    "元素ごとの初期磁気モーメント [μB]": Help(O, "元素ごとの初期磁気モーメント (μB/原子)。VASP の MAGMOM を POSCAR の原子の順に展開して書きます。空欄は 0。ISPIN = 2 のときだけ使われ、原子ごとの MAGMOM の欄とは併用できません。",
                                         "Initial magnetic moment per element (μB per atom), expanded into MAGMOM in POSCAR atom order; empty = 0. "
                                         "Used only with ISPIN = 2; cannot be combined with the per-atom MAGMOM field."),
    "DFT+U": Help(O, "局在した d・f 電子に Hubbard の U を掛ける補正。行ごとに元素 (いまの構造にあるものだけ)・殻 (例 3d、4f)・U [eV]・J [eV] を入れます。U に既定値はありません。表が空なら使いません。",
                  "Hubbard U correction for localized d and f electrons. Each row: element (only those in the current structure), shell (e.g. 3d, 4f), U [eV], J [eV]. "
                  "U has no default; an empty table means no DFT+U."),
    "LDAUTYPE": Help(O, "VASP の DFT+U の形式。2 (Dudarev、VASP の既定) は U − J だけが効き、1 は Liechtenstein、4 は 1 と同じで LSDA の交換分裂なし。",
                     "VASP DFT+U flavour: 2 (Dudarev, the VASP default) depends only on U − J; 1 is Liechtenstein; 4 is as 1 without LSDA exchange splitting."),
    "starting_magnetization (元素ごと)": Help(O, "pw.x の starting_magnetization (元素ごとの初期の磁化)。絶対値が 1 未満なら価電子あたりの割合です。空欄は指定しない。nspin = 2 のときだけ使われます。",
                                           "pw.x starting_magnetization per element; a magnitude below 1 is a fraction of the valence charge. Empty = not set. Used only with nspin = 2."),
    "HUBBARD の射影": Help(O, "QE の HUBBARD カードの射影 (U を掛ける占有数の数え方)。atomic が QE の既定。QE の生成器は U だけを書き、J は書きません。",
                         "Projector of the QE HUBBARD card (how occupations for U are counted); atomic is the QE default. The QE generator writes U only, not J."),
    "元素ごとの MAGNETIZATION": Help(O, "CP2K の KIND の MAGNETIZATION (原子の初期推定に足す α − β の電子数)。空欄は指定しない。スピン分極 (UKS) のときだけ使われます。",
                                  "CP2K KIND MAGNETIZATION (α − β electrons added to the atomic initial guess). Empty = not set. Used only with spin polarization (UKS)."),
    "PLUS_U_METHOD": Help(O, "CP2K の DFT+U で占有数を数える方法。MULLIKEN (CP2K の既定)、LOWDIN、MULLIKEN_CHARGES。",
                          "How CP2K counts occupations for DFT+U: MULLIKEN (the CP2K default), LOWDIN or MULLIKEN_CHARGES."),
    "プロファイル": Help(R, "cluster.toml に書いた実行先。local (この PC で bash submit.sh) か、PBS / Slurm のクラスタ。", "A target from cluster.toml: local (bash submit.sh on this machine) or a PBS / Slurm cluster."),
    "ノード数": Help(O, "使うノード数 (PBS の select、Slurm の --nodes)。", "Number of nodes (PBS select, Slurm --nodes)."),
    "ノードあたりのコア数": Help(O, "ノードあたりのコア数。", "Cores per node."),
    "ノードあたりの MPI プロセス数": Help(O, "ノードあたりの MPI プロセス数。mpirun -np に渡されます。OpenMP スレッド数との積がコア数以下になるようにします。", "MPI processes per node (mpirun -np). Processes × OpenMP threads should not exceed the cores."),
    "OpenMP スレッド数": Help(O, "1 プロセスあたりのスレッド数 (OMP_NUM_THREADS)。DFTB+ の OpenMP 版はこれで並列化します。", "Threads per process (OMP_NUM_THREADS); the OpenMP build of DFTB+ parallelizes with this."),
    "制限時間 (HH:MM:SS)": Help(O, "ジョブの制限時間。超えるとスケジューラが止めます。", "Job time limit; the scheduler kills the job beyond it."),
    "ジョブ名": Help(O, "スケジューラに見せる名前。", "Name shown by the scheduler."),
    "出力ディレクトリ": Help(R, "入力一式を書くディレクトリ。空でないディレクトリには上書きの確認をします。", "Directory where the files are written; a non-empty directory asks before overwriting."),
    "計算結果のディレクトリ": Help(R, "解析する計算結果のディレクトリ。生成・実行したものは自動で入ります。", "Directory of the run to analyze; filled automatically after generating / running."),
    "平衡化として捨てるフレーム数": Help(O, "MD の軌跡の先頭を平衡化とみなして捨てるフレーム数。RDF、MSD、温度の平均に効きます。", "Leading MD frames discarded as equilibration; affects RDF, MSD and the mean temperature."),
    "間引き (N フレームおき)": Help(O, "軌跡を N フレームおきに使います。RDF・MSD・z 方向の密度分布・書き出しに効き、1 フレームの時間は N 倍になります。1 なら全フレーム。",
                               "Uses every N-th trajectory frame; affects RDF, MSD, the z density and the export, and multiplies the time per frame by N. 1 = all frames."),
    "MSD の当てはめ範囲 [fs]": Help(O, "拡散係数を MSD の直線の傾きから求める時間の範囲 (始めと終わり)。3 次元なら D = 傾き / 6。空欄なら最大ずれ時間の 10〜50 %。",
                                "Time range (start and end) for obtaining the diffusion coefficient from the MSD slope. In 3D, D = slope / 6. Empty = 10–50% of the maximum lag time."),
    "MSD のメモリの上限 [MB]": Help(O, "MSD は全フレームの座標を持ちます。読む前に フレーム数 × 原子数 × 24 バイト を見積もり、この値を超えたら止めます。",
                                "The MSD keeps the coordinates of all frames. Frames × atoms × 24 bytes is estimated before reading, and the run stops above this limit."),
    "z 方向の密度分布": Help(O, "a-b 面に垂直な方向を区間に切り、元素ごとの数密度と質量密度を数えます。周期系の軌跡だけ。",
                         "Counts the number density of each element and the mass density in bins along the normal of the a-b plane; periodic trajectories only."),
    "z 密度の区間の幅 [Å]": Help(O, "z 方向の密度分布の区間の幅。", "Bin width of the density profile along z."),
    "時系列の統計 (ブロック平均と自己相関時間)": Help(O, "MD の温度・エネルギー・密度・圧力の時系列について、ブロック平均 (Flyvbjerg–Petersen) による平均値の誤差と、積分自己相関時間を並べます。",
                                          "For MD temperature, energy, density and pressure, lists the error of the mean by block averaging (Flyvbjerg-Petersen) and the integrated autocorrelation time."),
    "PDOS のファイルが無いときに理由を書く": Help(O, "PDOS はファイル (VASP の DOSCAR、QE の projwfc.x の出力) があれば描きます。これを入れると、無いときにその旨を要約に書きます。",
                                       "PDOS is drawn whenever the files exist (VASP DOSCAR, QE projwfc.x output); with this, the summary also says when they are missing."),
    "空間群の許容誤差 [Å]": Help(O, "spglib で空間群を求めるときの原子位置の許容誤差。カンマで複数を書くと、それぞれの結果を並べます。",
                             "Tolerance on atomic positions for spglib's space-group search; several comma-separated values are listed side by side."),
    "熱化学のモデル": Help(O, "振動数から熱化学 (ZPE・U・H・S・G / F) を ASE で計算するモデル。理想気体は並進・回転・振動・電子、ほかの 3 つは振動だけを含みます。選ばなければ計算しません。",
                       "Model for thermochemistry (ZPE, U, H, S, G / F) from the frequencies with ASE. The ideal gas includes translation, rotation, vibration and electrons; the other three only vibrations. Not computed unless chosen."),
    "熱化学の温度 [K]": Help(O, "熱化学を計算する温度。カンマで複数。モデルを選んだときに要ります。", "Temperatures for thermochemistry, comma separated; needed once a model is chosen."),
    "熱化学の圧力 [Pa]": Help(O, "理想気体のモデルで要ります。並進のエントロピーだけに効きます (1 atm = 101325 Pa、1 bar = 100000 Pa)。",
                          "Needed for the ideal gas; enters only the translational entropy (1 atm = 101325 Pa, 1 bar = 100000 Pa)."),
    "回転の対称数": Help(O, "理想気体のモデルで要ります。分子を回して同じ配置になる向きの数 σ。回転のエントロピーに効きます。",
                     "Needed for the ideal gas: the number σ of orientations that rotation maps onto the same configuration; enters the rotational entropy."),
    "分子の形": Help(O, "理想気体のモデルで要ります。直線・非直線・単原子で、使う振動の本数 (3N−5 / 3N−6 / 0) と回転の寄与が決まります。",
                   "Needed for the ideal gas: linear, nonlinear or monatomic fixes the number of modes used (3N−5 / 3N−6 / 0) and the rotational part."),
    "全スピン S": Help(O, "理想気体のモデルで要ります。電子のエントロピー k_B ln(2S+1) に効きます (一重項 0、二重項 0.5、三重項 1)。",
                     "Needed for the ideal gas; enters the electronic entropy k_B ln(2S+1) (singlet 0, doublet 0.5, triplet 1)."),
    "虚振動の扱い": Help(O, "使うモードに虚振動 (負の振動数) が残ったときに、除いて計算するか、計算しないか。虚振動が無ければ使いません。",
                     "What to do when imaginary (negative) frequencies remain among the modes used: drop them, or do not compute. Unused if there are none."),
    "除く低い振動の本数": Help(O, "調和・準調和・準 RRHO のモデルで要ります。振動数の 2 乗の小さい方から除く本数 (並進・回転にあたるモードなど)。",
                        "Needed for the harmonic, quasi-harmonic and quasi-RRHO models: how many modes with the smallest squared frequency are excluded (e.g. translations and rotations)."),
    "準調和の下限 [cm⁻¹]": Help(O, "準調和のモデルで要ります。これより低い振動数を、この値に上げてから数えます。", "Needed for the quasi-harmonic model: lower frequencies are raised to this value first."),
    "準 RRHO の τ [cm⁻¹]": Help(O, "準 RRHO のモデルで要ります。低い振動のエントロピーを自由回転子のものと混ぜる減衰関数の τ (Grimme 2012)。",
                              "Needed for the quasi-RRHO model: τ of the damping function that mixes low-mode entropies with free rotors (Grimme 2012)."),
    "UV-Vis の広げ方": Help(O, "ORCA の TD-DFT の吸収の遷移を、ガウス関数かローレンツ関数で広げてスペクトルにします。選ばなければ遷移の棒だけを描きます。",
                          "Broadens the ORCA TD-DFT absorption transitions with a Gaussian or Lorentzian; otherwise only the transition sticks are drawn."),
    "UV-Vis の半値全幅 [eV]": Help(O, "広げる関数の半値全幅。広げ方を選んだときに要ります。", "Full width at half maximum of the broadening; needed once a shape is chosen."),
    "分子を周期境界でつなぎ直す": Help(O, "書き出す前に、最初のフレームの結合で分子を決め、周期境界で切れた分子をつなぎ直します。結晶のように周期的につながった集まりはそのままです。",
                             "Before writing, molecules are taken from the bonds of the first frame and made whole across periodic boundaries; periodically connected groups such as crystals are left as they are."),
    "基準のディレクトリ": Help(R, "比べる計算のディレクトリを相対パスで書くときの基準。比べた表 (compare_*.csv) と図もここに書きます。",
                        "Base for relative run directories; the comparison tables (compare_*.csv) and figure are written here."),
    "機械学習ポテンシャルの種類": Help(R, "使う学習済みポテンシャルと、その ASE の calculator。MACE-MP と MACE-OFF は mace-torch の mace_mp / mace_off、CHGNet は chgnet の CHGNetCalculator です。"
                              "ADIT 自身はこれらを使わず、生成した run_mlip.py が走る環境で読み込みます。",
                              "Which trained potential and ASE calculator to use: MACE-MP and MACE-OFF are mace_mp / mace_off of mace-torch, CHGNet is CHGNetCalculator of chgnet. "
                              "adit itself does not use them; the generated run_mlip.py imports them where it runs."),
    "モデル": Help(O, "MACE の model 引数 (small のような名前か、モデルのファイルのパス)。ファイルを指定すると生成先へ写します。空欄なら、入っているバージョンの既定のモデルです (使ったバージョンは output.log に残ります)。CHGNet では空欄にします。",
                  "The model argument of MACE (a name such as small, or the path of a model file; a file is copied into the output). Empty = the default model of the installed version (recorded in output.log). Leave it empty for CHGNet."),
    "計算に使う装置 (device)": Help(O, "計算に使う装置 (cpu、cuda など)。空欄ならパッケージが選びます。", "Device used for the calculation (cpu, cuda, ...); empty lets the package choose."),
    "数値の精度 (dtype)": Help(O, "MACE の default_dtype (float32 / float64)。空欄ならパッケージの既定。CHGNet では使いません。",
                            "default_dtype of MACE (float32 / float64); empty = the package default. Unused for CHGNet."),
    "遷移状態の探索 (OptTS)": Help(O, "構造最適化を鞍点 (遷移状態) の探索にします (! OptTS)。計算の種類が構造最適化のときだけ書かれます。",
                              "Turns the optimization into a saddle-point (transition-state) search (! OptTS); written only when the task is a geometry optimization."),
    "最初にヘシアンを計算 (Calc_Hess)": Help(O, "探索を始める前に厳密なヘシアン (2 階微分) を計算します (%geom Calc_Hess true)。",
                                     "Computes an exact Hessian (second derivatives) before the search starts (%geom Calc_Hess true)."),
    "ヘシアンを計算し直す間隔 (Recalc_Hess)": Help(O, "何ステップごとにヘシアンを計算し直すか (%geom Recalc_Hess)。0 なら書きません (ORCA の既定)。",
                                         "How many steps between Hessian recalculations (%geom Recalc_Hess); 0 = not written (the ORCA default)."),
    "最後に振動数を計算 (Freq)": Help(O, "最適化のあとに振動解析を足します (! Freq)。虚振動が 1 つだけかを確かめるのに使われます。",
                              "Adds a frequency calculation after the optimization (! Freq); used to check whether there is exactly one imaginary mode."),
    "反応座標をたどる (IRC)": Help(O, "一点計算を ! Freq IRC にして、いまの構造を遷移状態として反応座標をたどります。計算の種類が一点計算のときだけ書かれます。",
                             "Makes the single point a ! Freq IRC run that follows the reaction path from the current structure as a transition state; written only when the task is a single point."),
    "IRC の反復の上限": Help(O, "%irc MaxIter。0 なら書きません (ORCA の既定)。", "%irc MaxIter; 0 = not written (the ORCA default)."),
    "IRC の向き": Help(O, "%irc Direction。both (ORCA の既定) は両向き、forward / backward は片側、down は下り方向だけ。",
                    "%irc Direction: both (the ORCA default), forward / backward for one side, or down."),
    "組の種類": Help(R, "同じ条件でまとめて作る計算の組。吸着 (スラブ・分子・吸着した構造)、反応 (係数 ν を付けた計算)、溶媒和 (気相と溶媒)。",
                   "The kind of set generated with identical settings: adsorption (slab, molecule, adsorbed), reaction (runs with coefficients ν), or solvation (gas phase and solvent)."),
    "分子の箱": Help(O, "吸着の組の分子を、そのままの構造で計算するか、スラブと同じセルの中心に置いて同じ周期で計算するか。",
                   "Whether the molecule of an adsorption set is computed as it is, or centered in the same cell as the slab with the same periodicity."),
    "スラブの構造": Help(O, "吸着の組のスラブの構造ファイル。空欄ならいまの画面の構造を使います。", "Structure file of the slab; empty = the structure on screen."),
    "分子の構造": Help(O, "吸着の組の分子の構造ファイル。空欄ならいまの画面の構造を使います。", "Structure file of the molecule; empty = the structure on screen."),
    "吸着した構造": Help(O, "スラブに分子が吸着した構造のファイル。空欄ならいまの画面の構造を使います。", "Structure file of the adsorbed state; empty = the structure on screen."),
    "画面の構造": Help(O, "現在の画面の構造を、吸着の組のスラブ・分子・吸着構造に使うか、extended XYZ として保存します。",
                       "Use the structure currently on screen as the slab, molecule, or adsorbed state in the set, or save it as extended XYZ."),
    "スラブの固定原子": Help(O, "スラブの計算で動かさない原子 (1 始まりの番号)。空欄なら固定しません。", "Atoms kept fixed in the slab run (1-based); empty = none."),
    "吸着した構造の固定原子": Help(O, "吸着した構造の計算で動かさない原子 (1 始まりの番号)。", "Atoms kept fixed in the adsorbed run (1-based)."),
    "反応に出てくる計算": Help(R, "反応の組の計算を 1 行に 1 つ。名前 (ディレクトリの名前になります)、構造のファイル (空欄なら画面の構造)、係数 ν (生成したファイルは正、反応物は負)、全電荷、スピン多重度。",
                       "One run per row: the name (it becomes the directory name), the structure file (empty = the structure on screen), the coefficient ν (products positive, reactants negative), the total charge and the spin multiplicity."),
    "溶媒側で変える手法の項目": Help(R, "溶媒側の計算で上書きする手法の項目を JSON で (例 {\"solvation\": \"alpb\", \"solvent\": \"water\"})。ここだけが気相側との違いになります。",
                          "Method items overridden for the solvated run, as JSON (e.g. {\"solvation\": \"alpb\", \"solvent\": \"water\"}); this is the only intended difference from the gas phase."),
    "気相側で変える手法の項目": Help(O, "気相側の計算で上書きする手法の項目を JSON で。空欄ならいまの画面の条件のままです。",
                          "Method items overridden for the gas-phase run, as JSON; empty = the settings on screen."),
    "組の定義ファイル (set.json)": Help(O, "組の定義を書いた JSON を使うときのパス (compare_sets.py の書式)。指定すると上の欄は使いません。",
                              "Path of a JSON set definition (the format of compare_sets.py); when given, the fields above are not used."),
    "作る配座の数": Help(R, "RDKit の ETKDG で作る配座の数。作ったあと力場で最適化し、重複を除きます。", "How many conformers RDKit ETKDG embeds; they are then optimized with a force field and de-duplicated."),
    "重複とみなす RMSD [Å]": Help(R, "すでに残した配座との RMSD (対称を考えて重ねた値) がこの値以下なら、重複として外します。既定値はありません。",
                            "A conformer is dropped as a duplicate when its RMSD (best symmetry-aware overlay) to a kept one is at most this; there is no default."),
    "力場": Help(O, "配座を粗く最適化する力場 (MMFF94 / MMFF94s / UFF)。エネルギーは並べるだけです。",
                "Force field used to relax the conformers (MMFF94 / MMFF94s / UFF); the energies are only listed."),
    "反復の上限": Help(O, "力場の最適化の反復の上限。既定の 200 は RDKit の既定値です。", "Maximum force-field iterations; the default 200 is RDKit's own default."),
    "全原子で測る": Help(O, "RMSD を水素も含めた全原子で測ります。外すと水素を除くので、OH の向きだけが違う配座は重複になります。",
                     "Measures the RMSD over all atoms including hydrogens; unticked it ignores hydrogens, so conformers differing only in OH orientation count as duplicates."),
    "残す数": Help(O, "重複を除いたあと、力場のエネルギーの低い順に残す数の上限。空欄なら全部。", "At most this many conformers are kept after de-duplication, lowest force-field energy first; empty = all."),
    "配座を作る SMILES": Help(O, "配座を作る分子の SMILES。画面の構造が SMILES や mol / sdf 由来でない (結合の情報が無い) ときに書きます。",
                          "SMILES of the molecule for the conformers; needed when the structure on screen has no bonding information (not from SMILES, mol or sdf)."),
    "始状態の構造": Help(O, "反応経路の始めの構造のファイル。空欄ならいまの画面の構造です。", "Structure file of the initial state; empty = the structure on screen."),
    "終状態の構造": Help(R, "反応経路の終わりの構造のファイル。始状態と原子の数・並び・周期・セルが同じである必要があります。",
                     "Structure file of the final state; it must have the same atoms in the same order, and the same periodicity and cell, as the initial one."),
    "中間の像の数": Help(R, "始状態と終状態のあいだに作る像の数 (端の 2 つは含みません)。", "How many images are made between the end points (not counting them)."),
    "NEB の作り方": Help(O, "計算コード自身の NEB (VASP・QE・CP2K) を書くか、像ごとの一点計算 (どのコードでも) にするか。",
                      "Whether to write the code's own NEB (VASP, QE, CP2K) or one single point per image (any code)."),
    "補間": Help(O, "中間の像の作り方 (ASE の NEB.interpolate)。idpp は原子間距離を補間し、linear は座標を直線で結びます。",
                "How the images are made (ASE NEB.interpolate): idpp interpolates interatomic distances, linear connects the coordinates by straight lines."),
    "climbing image": Help(O, "最高点の像を山の頂へ登らせる方法 (QE の CI_scheme、CP2K の CI-NEB)。VASP 本体のタグではないので、VASP では止まります。",
                           "Lets the highest image climb to the top (QE CI_scheme, CP2K CI-NEB). It is not a tag of plain VASP, so VASP stops."),
    "SPRING (VASP)": Help(O, "VASP の SPRING (ばね定数)。空欄なら書かず、VASP の既定のままです。", "The VASP SPRING (spring constant); empty = not written, so the VASP default applies."),
    "K_SPRING (CP2K)": Help(O, "CP2K の K_SPRING (ばね定数)。空欄なら書かず、CP2K の既定のままです。", "The CP2K K_SPRING; empty = not written, so the CP2K default applies."),
    "opt_scheme (QE)": Help(O, "neb.x の opt_scheme (像を動かす方法)。空欄なら neb.x の既定です。", "The opt_scheme of neb.x (how the images are moved); empty = the neb.x default."),
    "超格子の倍率": Help(R, "有限変位を入れる超格子の大きさ (例 2x2x2)。大きいほど遠くまでの力を数えられ、計算の数と原子数が増えます。",
                     "Size of the supercell used for the displacements (e.g. 2x2x2); a larger one captures longer-ranged forces and means more and bigger runs."),
    "変位の大きさ [Å]": Help(O, "原子をずらす距離。空欄なら phonopy (または ASE) の既定です。", "How far the atoms are displaced; empty = the phonopy (or ASE) default."),
    "変位の作り方": Help(O, "変位を phonopy で作るか、ASE の Phonons と同じ変位にするか。自動なら phonopy が入っていれば phonopy です。",
                     "Whether the displacements come from phonopy or from ASE's Phonons; automatic uses phonopy when it is installed."),
    "DOS の q 点のメッシュ": Help(O, "状態密度を求める q 点のメッシュ (例 10x10x10)。空欄なら状態密度を書きません (ADIT はメッシュの値を持ちません)。",
                           "q-point mesh for the phonon DOS (e.g. 10x10x10); empty = no DOS is written (ADIT has no default mesh)."),
    "DOS の幅 [THz]": Help(O, "ASE で集めるときに状態密度を広げるガウス関数の幅。ASE の DOS には必須で、phonopy (テトラヘドロン法) では使いません。",
                        "Width of the Gaussian broadening of the DOS for the ASE backend; required there and unused with phonopy (tetrahedron method)."),
    "歪みの大きさ": Help(R, "与える歪みの大きさをカンマで区切って (例 -0.01,0.01)。0 以外の異なる値を書きます。歪みなしの計算は自動で作ります。",
                     "Strain magnitudes separated by commas (e.g. -0.01,0.01); non-zero and distinct. The unstrained run is added automatically."),
    "歪みを与える成分": Help(O, "歪みを与える Voigt の成分 (1=xx 2=yy 3=zz 4=yz 5=xz 6=xy)。選んだ成分の列 C_ij だけが求まります。",
                      "Voigt components to strain (1=xx 2=yy 3=zz 4=yz 5=xz 6=xy); only the columns C_ij of the chosen components are obtained."),
    "作るもの": Help(R, "ORCA なら遷移状態の探索 (! OptTS)、IRC (! Freq IRC)、または段階に分けた両方。xtb と機械学習ポテンシャルなら ASE + Sella のスクリプト。",
                   "For ORCA: the transition-state search (! OptTS), the IRC (! Freq IRC), or both as two stages. For xtb and machine-learning potentials: an ASE + Sella script."),
    "IRC もたどる (Sella)": Help(O, "Sella で鞍点を見つけたあと、IRC を前向き・後ろ向きにたどるところまでスクリプトに書きます。",
                            "Also writes the forward and backward IRC into the Sella script, after the saddle point has been found."),
    "原子の選び方": Help(O, "解析する原子を絞ります。element O / index 1-10 / z < 10 / within 5 of index 3 を and・or・not でつなげます。空欄なら全原子です。",
         "Restrict the atoms to analyse. Combine element O, index 1-10, z < 10 and within 5 of index 3 with and, or and not. Empty means all atoms."),
    "RDF の元素の組": Help(O, "動径分布関数を出す元素の組です。セミコロンで区切ります。空欄なら現れる元素の全部の組み合わせを出します。",
         "Element pairs for the radial distribution function, separated by semicolons. Empty means every combination of the elements present."),
    "密度分布を取る軸": Help(O, "密度分布を取る軸です。界面が a 面や b 面に平行な系では c 以外を選びます。",
         "The axis along which the density profile is taken. Choose something other than c when the interface is normal to a or b."),
    "配位数のカットオフ [Å]": Help(O, "この距離より近い相手を数えて、原子ごとの配位数にします。どこで切るかは化学的な判断なので、ADIT は既定値を持ちません。",
         "Counts neighbours closer than this distance for each atom. Where to cut is a chemical judgement, so ADIT has no default."),
    "中心対称性の相手の数": Help(O, "中心対称性パラメータを出します。完全な結晶で 0 になります。どの値が欠陥かは判定しません。",
         "Computes the centrosymmetry parameter, which is zero for a perfect crystal. ADIT does not judge which value means a defect."),
    "Steinhardt q4・q6 のカットオフ [Å]": Help(O, "Steinhardt の秩序変数 q4 と q6 を出します。どの値がどの構造かは言いません (FCC は 0.19 と 0.57 が文献値です)。",
         "Computes the Steinhardt order parameters q4 and q6. ADIT does not say which value means which structure (0.19 and 0.57 are the literature values for FCC)."),
    "かたまりのカットオフ [Å]": Help(O, "この距離以内でつながった原子を 1 つのかたまりとして数えます。かたまりの正体 (分子か凝集体か) は言いません。",
         "Atoms connected within this distance are counted as one cluster. ADIT does not say what a cluster is (a molecule, an aggregate, ...)."),
    "結合角の分布の元素": Help(O, "中心の元素 (と、外側の元素) を指定して、結合角の分布を出します。山の帰属はしません。",
         "Give the central element (and optionally the outer element) for the bond-angle distribution. ADIT does not assign the peaks."),
    "結合角の分布のカットオフ [Å]": Help(O, "結合とみなす距離です。利用者が決めます。",
         "The distance treated as a bond. You choose it."),
    "構造因子 S(q) を出す": Help(O, "動径分布関数から構造因子 S(q) を出します (RDF が要ります)。打ち切りの影響が出る q を注に書きます。",
         "Computes the structure factor S(q) from the radial distribution function (the RDF is required). The note gives the q where truncation starts to matter."),
    "水素結合 (距離 [Å], 角度 [度])": Help(O, "水素結合を数えます。しきい値は必須です。GROMACS・VMD・cpptraj の既定値を注に並べますが、どれを採るかは利用者が決めます。",
         "Counts hydrogen bonds. The thresholds are required. The notes list the defaults used by GROMACS, VMD and cpptraj, but the choice is yours."),
    "CREST の配座の重みの温度 [K]": Help(O, "CREST の結果 (crest_conformers.xyz) を読むとき、この温度で Boltzmann の重み g·exp(−ΔE/kT)/Σ を出します。空欄なら相対エネルギーだけを出します。",
         "When a CREST result (crest_conformers.xyz) is read, Boltzmann weights g·exp(−ΔE/kT)/Σ are computed at this temperature. Empty = relative energies only."),
    "慣性半径 Rg の時系列": Help(O, "慣性半径と慣性主値の時系列を出します。大小の判定はしません。",
         "Time series of the radius of gyration and the principal moments. ADIT does not judge the values."),
    "3 次元の数密度の格子": Help(O, "軌跡を通した数密度を積んで cube に書き出します (VMD・VESTA・OVITO で開けます)。等値面は描きません。",
         "Accumulates the number density over the trajectory and writes a cube file (for VMD, VESTA and OVITO). No isosurface is drawn."),
    "Voronoi の体積と面の数": Help(O, "最後の構造の Voronoi 多面体の体積と面の数を出します。周期境界は像を足して扱います。",
         "Voronoi cell volumes and face counts for the last structure. Periodic images are added so the cells close."),
    "数える面の面積の下限 [Å²]": Help(O, "この面積より小さい面を数えません。面の数はこのしきい値で変わります。",
         "Faces smaller than this are not counted. The face count depends on this threshold."),
    "溶媒接触表面積 (半径の表, プローブ [Å])": Help(O, "Shrake–Rupley の方法で表面積を出します。半径の表 (bondi / ase) とプローブ半径は利用者が選びます。",
         "Shrake-Rupley surface area. You choose the radii set (bondi or ase) and the probe radius."),
    "距離の時系列 (原子の組)": Help(O, "指定した 2 原子の距離の時系列です。番号は 1 始まりで、セミコロンで複数書けます。",
         "Time series of the distance between two atoms. Indices start at 1; separate several pairs with semicolons."),
    "角度の時系列 (原子の組)": Help(O, "指定した 3 原子の角度の時系列です。真ん中が頂点です。",
         "Time series of the angle defined by three atoms; the middle one is the vertex."),
    "二面角の時系列 (原子の組)": Help(O, "指定した 4 原子の二面角の時系列です。",
         "Time series of the dihedral angle defined by four atoms."),
    "RMSD の基準フレーム": Help(O, "このフレーム (1 始まり) に重ね合わせて RMSD の時系列を出します。",
         "Superposes every frame on this one (1-based) and reports the RMSD over time."),
    "原子ごとの揺らぎ (RMSF)": Help(O, "重ね合わせたあとの、原子ごとの揺らぎです。",
         "Fluctuation of each atom after superposition."),
    "速度自己相関と振動スペクトル": Help(O, "速度の自己相関から振動スペクトルと、Green-Kubo の拡散係数を出します。標本化の刻みで見える上限 (ナイキスト) を注に書きます。",
         "Vibrational spectrum from the velocity autocorrelation, plus the Green-Kubo diffusion coefficient. The note gives the Nyquist limit of the sampling."),
    "イオンの電荷 (伝導度)": Help(O, "Nernst–Einstein の式でイオン伝導度を出します。電荷は利用者が渡します (ADIT は酸化数を決めません)。相関 (Haven 比) は 1 と置いた値です。",
         "Ionic conductivity from the Nernst-Einstein relation. You give the charge (ADIT does not assign oxidation states). Correlations (the Haven ratio) are taken as 1."),
    "伝導度の温度 [K]": Help(O, "イオン伝導度に使う温度です。空欄なら MD の設定温度か平均温度を使います。",
         "Temperature used for the conductivity. Empty means the MD target temperature or the average temperature."),
    "変位の基準フレーム": Help(O, "このフレームから最後のフレームまでの変位を出します。原子の並びが同じ順であることが前提です。",
         "Displacement from this frame to the last one. It assumes the atom order is unchanged."),
    "局所ひずみのカットオフ [Å]": Help(O, "近傍の相対位置の変化から、原子ごとの変形勾配とひずみを出します。当てはめの残差も出します。",
         "Deformation gradient and strain per atom from how the neighbours move. The fit residual is reported as well."),
    "主成分分析の成分の数": Help(O, "重ね合わせたあとの座標の主成分分析です。寄与率を必ず添えます。",
         "PCA of the coordinates after superposition. The explained variance is always given."),
    "分類する群の数 (k-means)": Help(O, "主成分の上で k-means で分けます。群の数は利用者が決めます (いくつが正しいかは判定しません)。",
         "k-means on the principal components. You choose the number of groups; ADIT does not judge it."),
    "自由エネルギー面の温度 [K]": Help(O, "距離・角度・二面角の時系列から A = -kT ln P を出します。1 つなら 1 次元、2 つなら 2 次元です。収束は判定しません。",
         "Computes A = -kT ln P from the distance, angle and dihedral series; one variable gives a curve, two give a map. Convergence is not judged."),
    "自由エネルギー面の区間の数": Help(O, "分布を数える区間の数です。点が少ないと空の区間が増えます (注に数を書きます)。",
         "Number of bins used for the distribution. With few points many bins stay empty (the count is in the notes)."),
    "自由エネルギーの単位": Help(O, "自由エネルギーの単位です。",
         "Unit used for the free energy."),
    "バンド図の縦軸の幅 [eV]": Help(O, "バンド図で、フェルミ準位の上下に描く幅です。",
         "How far above and below the Fermi level the band plot is drawn."),
    "有効質量に使う k 点の数": Help(O, "バンドの端の周りで 2 次式に当てはめる点の数です。広いほど当てはめの決定係数が下がります。",
         "Number of points fitted to a parabola around the band edge. A wider window lowers the fit quality."),
    "Bader の ACF.dat": Help(O, "外部の bader プログラム (GPL) が書いた ACF.dat を読みます。ADIT は分割を計算しません。",
         "Reads an ACF.dat written by the external bader program (GPL). ADIT does not do the partitioning itself."),
    "Bader の価電子数": Help(O, "原子の順に価電子数を渡すと、価電子との差 (いわゆる Bader 電荷) を出します。ADIT は推測しません。",
         "Give the valence electrons in atom order to get the difference from them (the Bader charge). ADIT does not guess them."),
    "粉末回折の線源": Help(O, "最後の構造から粉末 X 線回折の図を作ります。測定との一致は判定しません。",
         "Powder X-ray diffraction pattern from the last structure. Agreement with experiment is not judged."),
    "粉末回折の 2θ の範囲 [度]": Help(O, "図にする 2θ の範囲です。",
         "The 2-theta range shown in the plot."),
    "重ねる測定データのファイル": Help(O, "測定の回折図を重ねて描きます。強度は最大値で規格化します。一致の良し悪しは判定しません。",
         "Overlays a measured pattern, normalised to its maximum. ADIT does not judge how well they agree."),
    "粘度 (Green-Kubo)": Help(O, "圧力テンソルの非対角成分の自己相関から粘度を出します (出力にその成分が要ります)。収束は判定しません。",
         "Viscosity from the autocorrelation of the off-diagonal pressure tensor (the output must contain it). Convergence is not judged."),
    "面平均を取る軸": Help(O, "体積データ (cube・LOCPOT) を面で平均して、軸に沿った曲線にします。",
         "Averages volumetric data (cube, LOCPOT) over planes to give a curve along the axis."),
    "cube の値の単位": Help(O, "cube ファイルには単位が書かれていないので、利用者が言うときだけ換算します。",
         "Cube files do not state their unit, so the conversion is applied only when you say which one it is."),
    "仕事関数を出す": Help(O, "面平均の最大値 (真空準位) とフェルミ準位の差を出します。真空の領域があるかどうかは判定しません。",
         "Difference between the maximum of the plane average (the vacuum level) and the Fermi level. Whether a vacuum region exists is not judged."),
    "その場で計算する上限 [秒]": Help(O, "見積もりがこの秒数を超える重い解析は、その場では計算せず、計算機で実行用のファイルを用意します。",
         "Heavy analyses estimated to take longer than this are not computed here; files to run them elsewhere are written instead."),
    "計算コードの指定": Help(O, "入力ファイルが無く、出力だけ手元にあるときに、計算コードを自分で指定します (例 gaussian)。空欄なら入力ファイルから判定します。",
         "Name the code yourself when only the output file is at hand (e.g. gaussian). Empty means it is detected from the input file."),
    "振動数の補正係数": Help(O, "振動数に掛ける係数です。調和振動数は測定より高く出るので、論文では 0.96 などを掛けます。ADIT は既定値を持たず、使った値を図と要約に書きます。",
         "Factor applied to the frequencies. Harmonic frequencies come out higher than experiment, so papers scale them by about 0.96. ADIT has no default and records the value you used."),
    "重ねる測定したスペクトル": Help(O, "赤外・ラマンの図に測定を重ねます。縦軸は互いの最大値で合わせるだけで、一致の良し悪しは判定しません。",
         "Overlays a measured spectrum on the IR and Raman plots. The vertical axes are matched at their maxima only, and the agreement is not judged."),
    "報告をまとめる": Help(O, "計算ディレクトリから、方法の節・条件の表・結果の表・再現パッケージ・入力の照合用のハッシュの照合を作ります。コマンドの adit-report と同じものです。",
         "Builds the methods section, the conditions table, the results table, the reproducibility bundle and the fingerprint check from your run directories. It is the same as the adit-report command."),
    "計算ディレクトリ (1 行に 1 つ)": Help(O, "spec.json のある計算ディレクトリです。複数 入れると 1 枚の表にまとめます。",
         "Run directories that contain spec.json; several of them are combined into one table."),
    "報告の言語": Help(O, "方法の節の言語です。both を選ぶと日本語のあとに英語を並べます。",
         "Language of the methods section; both puts the English text after the Japanese."),
    "方法の節 (Markdown)": Help(O, "論文・報告書の「方法」に貼る文の書き出し先です。空欄なら画面に出すだけです。",
         "Where to write the methods text for a paper or report; empty means it is only shown on screen."),
    "条件の表 (CSV)": Help(O, "複数の計算の条件を 1 枚の表にした CSV の書き出し先です。",
         "Where to write a CSV that puts the conditions of several runs in one table."),
    "結果の表 (CSV)": Help(O, "最終エネルギー・平均温度・正常終了などを 1 枚の表にした CSV の書き出し先です。走っていない計算もそう書きます。",
         "Where to write a CSV of final energies, average temperatures and completion status; runs that have not been executed are marked as such."),
    "再現パッケージ (.zip)": Help(O, "再現に要るファイルと manifest.json をまとめた .zip (またはディレクトリ) の書き出し先です。すでにあるものには書きません。",
         "Where to write a .zip (or directory) with the files needed to reproduce the runs plus manifest.json; an existing path is never overwritten."),
    "入力の照合用のハッシュを照合する": Help(O, "生成したときに記録した SHA-256 と、いまのファイルを突き合わせます。一致 / 不一致 / 記録が無くて確かめられない の 3 つを出します。",
         "Compares the SHA-256 recorded at generation time with the files as they are now, reporting match, differ, or no record."),
    "報告を作る": Help(O, "上の指定で報告を作ります。",
         "Builds the report with the settings above."),
    "図の線の色": Help(O, "図の線に順に使う色です。カンマで区切ります。空欄なら matplotlib の既定です。",
         "Colors used for the lines, in order, separated by commas. Empty uses the matplotlib default."),
    "目盛りの向き": Help(O, "目盛りを内向き (in) にするか外向き (out) にするかです。論文誌の指定に合わせるときに使います。",
         "Whether ticks point inwards (in) or outwards (out); useful for matching a journal's style."),
    "目盛り線": Help(O, "目盛り線を引く軸です。none なら引きません。",
         "Which axes get grid lines; none draws no grid."),
    "グラフを囲む枠": Help(O, "グラフの枠です。all は四方、left-bottom は左と下だけ、none は枠なしです。",
         "The frame around the plot: all four sides, only left and bottom, or none."),
    "線の太さ [pt]": Help(O, "図の線の太さです。",
         "Width of the lines in the figures."),
    "図の文字の大きさ [pt]": Help(O, "図の中の文字の大きさです。",
         "Font size used inside the figures."),
    "図の解像度 [dpi]": Help(O, "図を保存するときの解像度です。論文に貼るときは 300 以上にします。",
         "Resolution used when saving the figures; 300 or more is usual for publication."),
    "図の追加の形式": Help(O, "PNG に加えて出す図の形式です (svg / pdf / eps)。Word や LaTeX に貼るとき、拡大しても粗くなりません。カンマで複数 書けます。",
         "Extra formats for the figures besides PNG (svg, pdf, eps); these stay sharp when enlarged in Word or LaTeX. Several can be given, separated by commas."),
}


def help_for(label: str) -> Help | None:
    return HELP.get(label)
