
from __future__ import annotations

import json
from pathlib import Path
from typing import Callable

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (QAbstractItemView, QCheckBox, QComboBox, QDialog, QFileDialog, QFormLayout, QHBoxLayout, QHeaderView,
                               QLabel, QLineEdit, QListWidget, QListWidgetItem, QMessageBox, QPlainTextEdit, QPushButton,
                               QTableWidget, QVBoxLayout, QWidget)

from adit.gui.style import GROUP_SPACING, PANEL_MARGIN, ROW_SPACING
from adit.gui.widgets import add_row, confirm_overwrite
from adit.lang import L
from adit.web.codefields import (STAGE_COLUMNS, carry_table, continuation_summary, row_from_stage, stage_choices, stage_column_titles,
                                  stage_from_row)


def _buttons(ok_text: str, dialog: QDialog) -> tuple[QHBoxLayout, QPushButton, QPushButton]:
    cancel = QPushButton(L("キャンセル", "Cancel")); ok = QPushButton(ok_text); ok.setObjectName("primary"); ok.setDefault(True)
    cancel.clicked.connect(dialog.reject)
    row = QHBoxLayout(); row.addStretch(); row.addWidget(cancel); row.addWidget(ok)
    return row, cancel, ok


def _hint(text: str) -> QLabel:
    w = QLabel(text); w.setObjectName("hint"); w.setWordWrap(True)
    return w


def _folder_row(edit: QLineEdit, title: str, parent: QWidget) -> QHBoxLayout:
    btn = QPushButton(L("参照…", "Browse…"))

    def choose() -> None:
        start = edit.text().strip() or str(Path.home())
        d = QFileDialog.getExistingDirectory(parent, title, str(Path(start).expanduser().parent))
        if d:
            edit.setText(d)
    btn.clicked.connect(choose)
    row = QHBoxLayout(); row.addWidget(edit, 1); row.addWidget(btn)
    edit.browse = btn
    return row


def _generator_error(ex: Exception) -> str:
    from pydantic import ValidationError as PydanticError
    if isinstance(ex, PydanticError):
        from adit.validate_types import friendly_pydantic
        return friendly_pydantic(ex)
    return str(ex)


class ContinueDialog(QDialog):

    def __init__(self, make_conditions: Callable, default_dir: str = "", parent: QWidget | None = None):
        super().__init__(parent)
        self.setWindowTitle(L("前の計算の続きを作る", "Continue a previous calculation"))
        self.make_conditions = make_conditions
        self.spec = None
        self.folder = QLineEdit(default_dir); self.folder.setPlaceholderText(L("前の計算のディレクトリ (中に spec.json がある)", "directory of the previous run (contains spec.json)"))
        self.found = _hint("")
        self.velocities = QCheckBox(L("速度を引き継ぐ (前も今回も MD のとき)", "Carry over the velocities (when both runs are MD)")); self.velocities.setChecked(True)
        self.keep = QCheckBox(L("計算の条件はいまの画面の値を使う (外すと前の計算と同じ条件)", "Use the current settings for the conditions (untick for the previous run's conditions)"))
        self.table = _hint(carry_table())
        self.table.setMinimumHeight(self.table.fontMetrics().lineSpacing() * 10 + 12)
        row, _, self.btn_ok = _buttons(L("続きを作る", "Continue"), self)
        form = QFormLayout(); form.setVerticalSpacing(ROW_SPACING)
        add_row(form, L("前の計算のディレクトリ", "Previous run directory"), _folder_row(self.folder, L("前の計算のディレクトリ", "Previous run directory"), self),
                help_text=L("ADIT が生成して、計算が最後まで走ったディレクトリ。最終構造 (MD なら速度も) を読みます。",
                            "A directory generated by ADIT whose calculation has finished; its final structure (and MD velocities) is read."))
        form.addRow(self.found)
        form.addRow(self.velocities); form.addRow(self.keep)
        lay = QVBoxLayout(self); lay.setContentsMargins(PANEL_MARGIN, PANEL_MARGIN, PANEL_MARGIN, PANEL_MARGIN); lay.setSpacing(GROUP_SPACING)
        lay.addLayout(form); lay.addWidget(self.table); lay.addLayout(row)
        self.setMinimumWidth(680)
        self.folder.textChanged.connect(self._look)
        self.btn_ok.clicked.connect(self.make)
        self._look()

    def _look(self, *_) -> None:
        from adit.spec import CalculationSpec
        d = Path(self.folder.text().strip()).expanduser()
        if not self.folder.text().strip():
            self.found.setText(""); return
        sp = d / "spec.json"
        if not sp.is_file():
            self.found.setText(L(f"{d} に spec.json がありません", f"{d} has no spec.json")); return
        try:
            prev = CalculationSpec.load(sp)
        except Exception as ex:
            self.found.setText(L(f"spec.json を読めません: {ex}", f"cannot read spec.json: {ex}")); return
        from adit.stages import _describe
        self.found.setText(L(f"前の計算: {prev.method.code}、{_describe(prev)}、{len(prev.structure.atoms.symbols)} 原子",
                             f"Previous run: {prev.method.code}, {_describe(prev)}, {len(prev.structure.atoms.symbols)} atoms"))

    def make(self) -> None:
        from adit.continuation import ContinuationError, continue_from
        from adit.project import ProjectError
        if not self.folder.text().strip():
            QMessageBox.warning(self, L("続きを作れません", "Cannot continue"), L("前の計算のディレクトリを指定してください。", "Choose the previous run directory.")); return
        try:
            cond = self.make_conditions() if self.keep.isChecked() else None
            self.spec = continue_from(self.folder.text().strip(), cond, velocities=self.velocities.isChecked())
        except (ContinuationError, ProjectError, ValueError, OSError) as ex:
            QMessageBox.critical(self, L("続きを作れません", "Cannot continue"), _generator_error(ex)); return
        self.accept()

    def summary(self) -> str:
        return continuation_summary(self.spec) if self.spec is not None else ""


_choices = stage_choices


class StagesDialog(QDialog):

    def __init__(self, default_dir: str, make_spec: Callable, cfg, parent: QWidget | None = None):
        super().__init__(parent)
        self.setWindowTitle(L("段階に分けて生成", "Staged calculation"))
        self.make_spec, self.cfg = make_spec, cfg
        self.out_dir: Path | None = None
        self.backup_dir: Path | None = None
        self.dirs: list[Path] = []
        self.table = QTableWidget(0, len(STAGE_COLUMNS))
        self.table.setHorizontalHeaderLabels(stage_column_titles())
        self.table.verticalHeader().setVisible(True)
        self.table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.table.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        hh = self.table.horizontalHeader(); hh.setSectionResizeMode(QHeaderView.ResizeMode.ResizeToContents)
        hh.setSectionResizeMode(len(STAGE_COLUMNS) - 1, QHeaderView.ResizeMode.Stretch)
        self.table.setMinimumHeight(220)
        self.btn_add = QPushButton(L("段階を追加", "Add stage")); self.btn_del = QPushButton(L("選んだ段階を削除", "Remove selected"))
        self.btn_up = QPushButton(L("上へ", "Up")); self.btn_down = QPushButton(L("下へ", "Down"))
        self.btn_load = QPushButton(L("stages.json を読む…", "Load stages.json…")); self.btn_save = QPushButton(L("stages.json に保存…", "Save stages.json…"))
        for b in (self.btn_load, self.btn_save):
            b.setObjectName("link")
        self.folder = QLineEdit(default_dir)
        self.output_path = _hint("")
        self.note = _hint(L("空欄の列は、いまの画面の値のままです。各段階は、いまの画面の設定にその段階の列だけを上書きしたものです (前の段階の値は受け継ぎません)。"
                            "2 段階目からは、実行する直前に前の段階の最終構造 (MD が続くなら速度も) を写します。計算コードは全段階で同じです。",
                            "Empty cells keep the current settings. Each stage is the current settings with only that stage's cells overridden "
                            "(values are not inherited from the previous stage). From stage 2 on, the final structure of the previous stage "
                            "(and the velocities if MD continues) is copied right before it runs. All stages use the same code."))
        self.cost = _hint(L("段階の数だけ計算が増えます。大きな系は、この PC ではなくクラスタで実行してください。",
                            "Each stage is a separate calculation. Run large systems on a cluster rather than on this PC."))
        row, _, self.btn_ok = _buttons(L("段階に分けて生成", "Generate stages"), self)
        tools = QHBoxLayout()
        for b in (self.btn_add, self.btn_del, self.btn_up, self.btn_down):
            tools.addWidget(b)
        tools.addStretch(1); tools.addWidget(self.btn_load); tools.addWidget(self.btn_save)
        form = QFormLayout(); form.setVerticalSpacing(ROW_SPACING)
        add_row(form, L("保存先", "Output directory"), _folder_row(self.folder, L("保存先", "Output directory"), self),
                help_text=L("この中に段階ごとのディレクトリ (例 stage_01_min) と、段階を順に実行する submit.sh を作ります。",
                            "One directory per stage (e.g. stage_01_min) and a submit.sh that runs them in order are created inside it."))
        form.addRow(self.output_path)
        lay = QVBoxLayout(self); lay.setContentsMargins(PANEL_MARGIN, PANEL_MARGIN, PANEL_MARGIN, PANEL_MARGIN); lay.setSpacing(GROUP_SPACING)
        lay.addWidget(self.note); lay.addWidget(self.table, 1); lay.addLayout(tools); lay.addLayout(form); lay.addWidget(self.cost); lay.addLayout(row)
        self.setMinimumWidth(1100)
        self.btn_add.clicked.connect(lambda: self.add_stage())
        self.btn_del.clicked.connect(self._delete)
        self.btn_up.clicked.connect(lambda: self._move(-1)); self.btn_down.clicked.connect(lambda: self._move(1))
        self.btn_load.clicked.connect(self._load); self.btn_save.clicked.connect(self._save)
        self.btn_ok.clicked.connect(self.generate)
        self.folder.textChanged.connect(self._show_output_path)
        self.add_stage()
        self._show_output_path()

    def _show_output_path(self, *_) -> None:
        path = self.folder.text().strip()
        self.output_path.setText(L(f"段階のディレクトリはこの場所に作ります: {path}", f"The stage directories will be created here: {path}") if path else "")

    def add_stage(self, row: dict | None = None) -> None:
        r = self.table.rowCount(); self.table.insertRow(r)
        row = row or {}
        for c, col in enumerate(STAGE_COLUMNS):
            ch = _choices(col)
            if ch is not None:
                w = QComboBox()
                w.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToMinimumContentsLengthWithIcon)
                w.setMinimumContentsLength(18 if col == "type" else 9)
                for k, t in ch:
                    w.addItem(t, k)
                cur = row.get(col, "auto" if col == "velocities" else "")
                if w.findData(cur) < 0 and cur:
                    w.addItem(cur, cur)
                w.setCurrentIndex(max(0, w.findData(cur)))
            else:
                w = QLineEdit(str(row.get(col, "")))
                if col == "name":
                    w.setPlaceholderText(L("例 nvt", "e.g. nvt"))
                elif col == "extra":
                    w.setPlaceholderText('{"method": {"pcoupl": "C-rescale"}}')
            w.setAccessibleName(f"{stage_column_titles()[c]} {r + 1}")
            self.table.setCellWidget(r, c, w)
        self.table.selectRow(r)

    def _delete(self) -> None:
        r = self.table.currentRow()
        if r >= 0:
            self.table.removeRow(r)

    def _move(self, d: int) -> None:
        r = self.table.currentRow(); t = r + d
        if r < 0 or not (0 <= t < self.table.rowCount()):
            return
        rows = self.rows()
        rows[r], rows[t] = rows[t], rows[r]
        self.set_rows(rows); self.table.selectRow(t)

    def rows(self) -> list[dict]:
        out = []
        for r in range(self.table.rowCount()):
            row = {}
            for c, col in enumerate(STAGE_COLUMNS):
                w = self.table.cellWidget(r, c)
                row[col] = (w.currentData() or "") if isinstance(w, QComboBox) else w.text()
            out.append(row)
        return out

    def set_rows(self, rows: list[dict]) -> None:
        self.table.setRowCount(0)
        for row in rows:
            self.add_stage(row)

    def stages_data(self, base_type: str) -> dict:
        stages = []
        for i, row in enumerate(self.rows(), start=1):
            s = stage_from_row(row, len(stages) + 1, base_type)
            if s is not None:
                stages.append(s)
        return {"stages": stages}

    def _load(self) -> None:
        path, _ = QFileDialog.getOpenFileName(self, "stages.json", "", "JSON (*.json)")
        if path:
            self.load_file(path)

    def load_file(self, path: str | Path) -> None:
        from adit.stages import StageError, parse_stages
        try:
            data = json.loads(Path(path).read_text(encoding="utf-8"))
            items = data.get("stages") if isinstance(data, dict) else data
            if isinstance(items, list):
                items = [{k: v for k, v in it.items() if k != "dir"} if isinstance(it, dict) else it for it in items]
            parse_stages({"stages": items})
        except (OSError, ValueError, StageError) as ex:
            QMessageBox.critical(self, L("読めません", "Cannot read"), str(ex)); return
        self.set_rows([row_from_stage(s) for s in items])

    def _save(self) -> None:
        try:
            data = self.stages_data(self._base_type())
        except ValueError as ex:
            QMessageBox.critical(self, L("保存できません", "Cannot save"), str(ex)); return
        path, _ = QFileDialog.getSaveFileName(self, "stages.json", "stages.json", "JSON (*.json)")
        if path:
            try:
                Path(path).write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            except OSError as ex:
                QMessageBox.critical(self, L("保存できません", "Cannot save"), str(ex))

    def _base_type(self) -> str:
        try:
            return self.make_spec().task.type
        except Exception:
            return ""

    def generate(self) -> None:
        from adit.config import ConfigError
        from adit.project import ProjectError
        from adit.stages import StageError, parse_stages, write_stages

        if not self.folder.text().strip():
            QMessageBox.warning(self, L("生成できません", "Cannot generate"), L("保存先を指定してください。", "Choose an output directory.")); return
        out = Path(self.folder.text().strip()).expanduser()
        try:
            spec = self.make_spec()
            data = self.stages_data(spec.task.type)
            stages = parse_stages(data)
            overwrite, keep = confirm_overwrite(self, out)
            if overwrite is None:
                return
            dirs = write_stages(spec, self.cfg, out, stages, overwrite=overwrite)
            self.backup_dir = keep.finish() if keep is not None else None
        except (StageError, ProjectError, ConfigError, ValueError, OSError) as ex:
            QMessageBox.critical(self, L("生成できません", "Cannot generate"), _generator_error(ex)); return
        self.out_dir, self.dirs = out, dirs
        names = "\n".join(f"  {d.name}" for d in dirs)
        QMessageBox.information(self, L("生成しました", "Generated"), L(
            f"{out} の中に {len(dirs)} 段階のディレクトリを作りました。\n{names}\n\n"
            "次にすること\n"
            "1. この PC なら、保存先で bash submit.sh を実行すると段階を順に実行します。クラスタなら、保存先の README.txt にある "
            "依存付きの投入の例 (前の段階が終わってから次の段階が始まる) を使います。\n"
            "2. 各段階が終わったら、解析タブでその段階のディレクトリを解析します。",
            f"Created {len(dirs)} stage directories in {out}:\n{names}\n\n"
            "Next steps\n"
            "1. On this PC, run bash submit.sh in the output directory to run the stages in order. On a cluster, use the dependent "
            "submission example in README.txt there (each stage starts after the previous one finishes).\n"
            "2. When a stage has finished, analyze its directory in the Analysis tab."))
        self.accept()


class TemplateLoadDialog(QDialog):

    def __init__(self, cfg, parent: QWidget | None = None):
        super().__init__(parent)
        from adit.templates import list_templates, template_dirs
        self.setWindowTitle(L("研究室の雛形を読み込む", "Load a group template"))
        self.chosen: str = ""
        self.list = QListWidget(); self.list.setMinimumHeight(220)
        self.infos = list_templates(cfg)
        for info in self.infos:
            text = f"{info.name}    {info.code}" + (f"    {info.comment}" if info.comment else "")
            if info.error:
                text = f"{info.name}    " + L(f"(読めません: {info.error})", f"(cannot read: {info.error})")
            it = QListWidgetItem(text); it.setData(Qt.ItemDataRole.UserRole, info.name); it.setToolTip(str(info.path))
            if info.error:
                it.setFlags(it.flags() & ~Qt.ItemFlag.ItemIsEnabled)
            self.list.addItem(it)
        where = ", ".join(str(d) for d in template_dirs(cfg))
        self.note = _hint(L(f"雛形は構造を除いた計算の条件です。読み込むと、いまの構造はそのままで、条件だけが雛形の値になります。置き場所: {where}",
                            f"A template holds the calculation conditions without a structure. Loading it keeps the current structure and "
                            f"replaces only the conditions. Folders: {where}"))
        self.empty = _hint(L("雛形がまだありません。「今の設定を雛形として保存…」で作れます。置き場所は環境設定の templates_dir で変えられます。",
                             "No templates yet. Create one with \"Save the current settings as a template…\"; the folder can be set as templates_dir in the preferences."))
        self.empty.setVisible(not self.infos)
        row, _, self.btn_ok = _buttons(L("読み込む", "Load"), self)
        lay = QVBoxLayout(self); lay.setContentsMargins(PANEL_MARGIN, PANEL_MARGIN, PANEL_MARGIN, PANEL_MARGIN); lay.setSpacing(GROUP_SPACING)
        lay.addWidget(self.note); lay.addWidget(self.list, 1); lay.addWidget(self.empty); lay.addLayout(row)
        self.setMinimumWidth(640)
        self.list.itemDoubleClicked.connect(lambda _it: self._ok())
        self.btn_ok.clicked.connect(self._ok)

    def select(self, name: str) -> None:
        for i in range(self.list.count()):
            if self.list.item(i).data(Qt.ItemDataRole.UserRole) == name:
                self.list.setCurrentRow(i)

    def _ok(self) -> None:
        it = self.list.currentItem()
        if it is None or not (it.flags() & Qt.ItemFlag.ItemIsEnabled):
            QMessageBox.warning(self, L("読み込めません", "Cannot load"), L("雛形を選んでください。", "Choose a template.")); return
        self.chosen = it.data(Qt.ItemDataRole.UserRole)
        self.accept()


class TemplateSaveDialog(QDialog):

    def __init__(self, cfg, make_spec: Callable, parent: QWidget | None = None):
        super().__init__(parent)
        from adit.templates import template_dirs
        self.setWindowTitle(L("今の設定を雛形として保存", "Save the current settings as a template"))
        self.cfg, self.make_spec = cfg, make_spec
        self.path: Path | None = None
        self.name = QLineEdit(); self.name.setPlaceholderText(L("例 lab-vasp-pbe (英数字と . _ -)", "e.g. lab-vasp-pbe (letters, digits, . _ -)"))
        self.comment = QLineEdit(); self.comment.setPlaceholderText(L("雛形の説明 (任意)", "description (optional)"))
        self.where = _hint(L(f"保存先: {template_dirs(cfg)[0]}", f"Folder: {template_dirs(cfg)[0]}"))
        note = _hint(L("構造と、前の計算から引き継いだものは保存しません。計算コード・手法・計算の種類・k 点・実行環境の値を保存します。",
                       "The structure and anything carried over from a previous run are not saved; the code, method, task, k-points and target are."))
        row, _, self.btn_ok = _buttons(L("保存", "Save"), self)
        form = QFormLayout(); form.setVerticalSpacing(ROW_SPACING)
        add_row(form, L("雛形の名前", "Template name"), self.name, required=True,
                help_text=L("ファイル名になります (名前.json)。英数字で始め、英数字と . _ - だけを使います。", "Becomes the file name (name.json); starts with a letter or digit and uses only letters, digits, . _ -."))
        add_row(form, L("説明", "Description"), self.comment, help_text=L("一覧に出る説明。", "Shown in the template list."))
        lay = QVBoxLayout(self); lay.setContentsMargins(PANEL_MARGIN, PANEL_MARGIN, PANEL_MARGIN, PANEL_MARGIN); lay.setSpacing(GROUP_SPACING)
        lay.addLayout(form); lay.addWidget(self.where); lay.addWidget(note); lay.addLayout(row)
        self.setMinimumWidth(600)
        self.btn_ok.clicked.connect(self.save)

    def save(self) -> None:
        from adit.project import ProjectError
        from adit.templates import TemplateError, save_template
        try:
            spec = self.make_spec()
            try:
                self.path = save_template(spec, self.name.text().strip(), cfg=self.cfg, comment=self.comment.text().strip())
            except TemplateError as ex:
                if "already exists" not in str(ex) and "すでにあります" not in str(ex):
                    raise
                ans = QMessageBox.question(self, L("上書きの確認", "Overwrite?"), L(f"雛形 {self.name.text().strip()} はすでにあります。上書きしますか?",
                                                                                 f"The template {self.name.text().strip()} already exists. Overwrite it?"))
                if ans != QMessageBox.StandardButton.Yes:
                    return
                self.path = save_template(spec, self.name.text().strip(), cfg=self.cfg, comment=self.comment.text().strip(), overwrite=True)
        except (TemplateError, ProjectError, ValueError, OSError) as ex:
            QMessageBox.critical(self, L("保存できません", "Cannot save"), _generator_error(ex)); return
        self.accept()


__all__ = ["ContinueDialog", "StagesDialog", "TemplateLoadDialog", "TemplateSaveDialog"]
