
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from adit.lang import L
from adit.spec import CalculationSpec


@dataclass
class Item:
    dir: str
    spec: CalculationSpec
    readme: list[str] = field(default_factory=list)
    extra_texts: dict[str, str] = field(default_factory=dict)


def with_comment(spec: CalculationSpec, text: str) -> CalculationSpec:
    return spec.model_copy(update={"meta": spec.meta.model_copy(update={"comment": (spec.meta.comment + " " + text).strip()})})


def check_output(out: Path, overwrite: bool) -> None:
    from adit.project import OutputNotEmpty, ProjectError
    from adit.validate import output_dir_errors

    out = Path(out).expanduser()
    errs = output_dir_errors(out)
    if errs:
        raise ProjectError(L("次の点を直すと生成できます:", "fix the following to generate:") + "\n" + "\n".join(f"  - {e}" for e in errs), errs)
    if out.exists() and any(out.iterdir()) and not overwrite:
        raise OutputNotEmpty(L(f"出力先 {out} には、すでにファイルがあります。黙って上書きしないよう、何も書かずに止めました。",
                               f"The output directory {out} already contains files; nothing was written, to avoid overwriting them silently."))


def build_all(items: list[Item], cfg, out: Path) -> None:
    from adit.project import ProjectError, build_project

    for it in items:
        try:
            build_project(it.spec, cfg, output_dir=out / it.dir, extra_readme=it.readme)
        except ProjectError as ex:
            raise ProjectError(f"{it.dir}: {ex}", ex.errors) from ex


def write_items(items: list[Item], cfg, out: Path, *, overwrite: bool = False) -> list[Path]:
    from adit.project import write_project

    out = Path(out).expanduser()
    names = [it.dir for it in items]
    if len(set(names)) != len(names):
        raise ValueError(L(f"同じ名前のディレクトリが 2 つあります: {sorted({n for n in names if names.count(n) > 1})}",
                           f"two directories have the same name: {sorted({n for n in names if names.count(n) > 1})}"))
    check_output(out, overwrite)
    out.mkdir(parents=True, exist_ok=True)
    build_all(items, cfg, out)
    dirs = []
    for it in items:
        d = out / it.dir
        write_project(it.spec, cfg, d, overwrite=overwrite, extra_readme=it.readme)
        for rel, text in it.extra_texts.items():
            (d / rel).write_text(text, encoding="utf-8", newline="\n")
        dirs.append(d)
    return dirs


def write_json(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2, default=str) + "\n", encoding="utf-8")


def write_scan_json(out: Path, label: str, values: list[str], dirs: list[Path]) -> None:
    write_json(out / "scan.json", {"path": label, "values": list(values), "dirs": [d.name for d in dirs]})


def top_submit(dirs: list[Path], what: str) -> str:
    from adit import __version__

    names = " ".join(d.name for d in dirs)
    return ("#!/bin/bash\n"
            + L(f"# ADIT {__version__} が生成。{what}を 1 つずつ順に実行する (互いに独立なので、失敗しても次へ進む)\n",
                f"# generated by ADIT {__version__}. Runs the {what} one by one (they are independent, so a failure does not stop the rest)\n")
            + 'cd "$(dirname "$0")"\nfailed=""\n'
            + f"for d in {names}; do\n  echo \"== $d\"\n  bash \"$d/submit.sh\" || failed=\"$failed $d\"\ndone\n"
            + 'if [ -n "$failed" ]; then echo "failed:$failed" >&2; exit 1; fi\n')


def write_top(out: Path, cfg, spec: CalculationSpec, dirs: list[Path], readme_lines: list[str], what_ja: str, what_en: str) -> None:
    profile = cfg.profile(spec.runtime.profile)
    lines = list(readme_lines) + ["", L("== この PC で実行する ==", "== Run on this PC ==")]
    if profile.kind == "direct":
        (out / "submit.sh").write_text(top_submit(dirs, L(what_ja, what_en)), encoding="utf-8", newline="\n")
        try:
            (out / "submit.sh").chmod(0o755)
        except OSError:
            pass
        lines.append(L(f"  bash submit.sh   ({what_ja}を順に実行します。1 つずつ実行するなら、各ディレクトリで bash submit.sh)",
                       f"  bash submit.sh   (runs the {what_en} in order; or run bash submit.sh inside each directory)"))
    else:
        lines.append(L("  この生成したファイルはクラスタのプロファイル用です。この PC で実行するなら、プロファイルを direct のものにして生成し直します。",
                       "  These files are for a cluster profile; to run on this PC, generate again with a direct profile."))
    lines += ["", L("== クラスタで実行する (ADIT は投入しません) ==", "== Running on a cluster (ADIT does not submit) =="),
              L("  各ディレクトリの submit.sh をクラスタのプロファイルで生成したうえで、このディレクトリで次のように投入します (互いに独立)。",
                "  With each submit.sh generated for a cluster profile, submit them from this directory as below (they are independent)."),
              f"  PBS:   for d in {' '.join(d.name for d in dirs)}; do (cd $d && qsub submit.sh); done",
              f"  Slurm: for d in {' '.join(d.name for d in dirs)}; do (cd $d && sbatch submit.sh); done"]
    (out / "README.txt").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


__all__ = ["Item", "write_items", "write_json", "write_scan_json", "write_top", "with_comment", "check_output", "build_all"]
