"""Write the methods section and the reproducibility package for finished runs. Only recorded facts are written."""

from __future__ import annotations

from adit.errors import AditValueError
import argparse
import csv
import io
import json
import shutil
import zipfile
from dataclasses import dataclass, field
from pathlib import Path

from adit import lang
from adit.lang import L
from adit.provenance import read_provenance, sha256_file, verify_inputs

MANIFEST_FILE = "manifest.json"
METHODS_FILE = "methods.md"
_UNITS = (
    ("_ev_per_ang", "eV/Å"), ("_per_bar", "1/bar"), ("_kj_per_mol_nm", "kJ/mol/nm"), ("_cm1", "cm⁻¹"),
    ("_ha", "Hartree"), ("_ry", "Ry"), ("_ev", "eV"), ("_nm", "nm"), ("_ang", "Å"), ("_fs", "fs"),
    ("_ps", "ps"), ("_k", "K"), ("_bar", "bar"), ("_mb", "MB"), ("_gb", "GB"), ("_steps", ""),
)
_CODE_UNITS = {
    "espresso": {"ecutwfc": "Ry", "ecutrho": "Ry", "conv_thr": "Ry", "degauss": "Ry"},
    "abinit": {"tolerance_value": {"toldfe": "Hartree", "tolvrs": "", "toldff": "Hartree/Bohr",
                                   "tolrff": "", "tolwfr": ""}},

    "dftbplus": {"scc_tolerance": "e"},
    "vasp": {"encut": "eV", "ediff": "eV", "ediffg": "eV/Å", "sigma": "eV"},
    "xtb": {"accuracy": ""},
}
_SKIP_METHOD_FIELDS = ("code",)
_TASK_FIELDS = ("type", "max_steps", "force_tolerance_ev_per_ang", "relax_cell", "optimizer")
_MD_FIELDS = ("ensemble", "thermostat", "temperature_k", "timestep_fs", "steps", "dump_interval",
              "coupling_time_fs", "pressure_bar", "barostat_time_fs")


class ReportError(AditValueError):
    pass


@dataclass
class RunReport:

    run_dir: Path
    spec: object | None = None
    provenance: dict = field(default_factory=dict)
    code_version: str = ""
    analysis_summary: str = ""
    notes: list[str] = field(default_factory=list)

    @property
    def code(self) -> str:
        return self.spec.method.code if self.spec is not None else ""


def code_display_name(code: str) -> str:
    from adit.project import code_display_name as _name

    return _name(code)


def tidy_version(text: str) -> str:
    import re

    line = re.sub(r"\s+", " ", text).strip()
    line = re.sub(r"^adit-[a-z0-9]+:\s*", "", line)
    return line.strip(" .*|\t")




def load_run_report(run_dir: Path | str) -> RunReport:
    """Read one run directory. Raises ReportError when spec.json is missing."""
    from adit.spec import CalculationSpec

    d = Path(run_dir).expanduser()
    if not d.is_dir():
        raise ReportError(L(f"ディレクトリがありません: {d}", f"directory not found: {d}"))
    spec_path = d / "spec.json"
    if not spec_path.is_file():
        raise ReportError(L(f"{d} に spec.json がありません (ADIT が生成したディレクトリを指定してください)",
                            f"{d} has no spec.json (give a directory generated by ADIT)"))
    try:
        spec = CalculationSpec.load(spec_path)
    except Exception as ex:
        raise ReportError(L(f"{spec_path} を読めません: {ex}", f"cannot read {spec_path}: {ex}")) from ex
    report = RunReport(run_dir=d, spec=spec, provenance=read_provenance(d) or {})
    version_file = d / "code_version.txt"
    if version_file.is_file():
        text = version_file.read_text(encoding="utf-8", errors="replace").strip()
        report.code_version = tidy_version(text.splitlines()[0]) if text else ""
    if not report.code_version:
        report.notes.append(L("計算コードのバージョンは未記録です (実行する前か、この計算コードのバージョンの行を確かめていません)",
                              "the code version is not recorded (the run has not finished, or the version line of this code was not verified)"))
    summary = d / "analysis" / "summary.txt"
    if summary.is_file():
        report.analysis_summary = summary.read_text(encoding="utf-8", errors="replace").strip()
    if not report.provenance:
        report.notes.append(L("作成時の記録 (生成した ADIT のバージョン・ファイルの照合用のハッシュ) が spec.json にありません",
                              "the provenance (ADIT version, file fingerprints) is not in spec.json"))
    return report


def _unit_of(name: str, spec=None) -> str:
    for suffix, unit in _UNITS:
        if name.endswith(suffix):
            return unit
    if spec is not None:
        table = _CODE_UNITS.get(spec.method.code, {})
        unit = table.get(name, "")
        if isinstance(unit, dict):
            return unit.get(getattr(spec.method, "tolerance", ""), "")
        return unit
    return ""


def _is_empty(value) -> bool:
    return value is None or value == "" or value == {} or value == [] or value is False


def _value_text(value, machine: bool = False) -> str:
    if isinstance(value, bool):
        return ("true" if value else "false") if machine else (L("はい", "yes") if value else L("いいえ", "no"))
    if isinstance(value, float):
        return f"{value:g}"
    if isinstance(value, (list, tuple)):
        return ", ".join(_value_text(v, machine) for v in value)
    if isinstance(value, dict):
        return ", ".join(f"{k}: {_value_text(v, machine)}" for k, v in value.items())
    return str(value)


def condition_rows(report: RunReport, machine: bool = False) -> list[tuple[str, str, str]]:
    spec = report.spec
    if spec is None:
        return []
    rows: list[tuple[str, str, str]] = []
    method = spec.method.model_dump(mode="json")
    for name, value in method.items():
        if name in _SKIP_METHOD_FIELDS or _is_empty(value):
            continue
        if isinstance(value, (int, float)) and not isinstance(value, bool) and value == 0 and "seed" not in name:
            continue
        rows.append((f"method.{name}", _value_text(value, machine), _unit_of(name, spec)))
    task = spec.task.model_dump(mode="json")
    skip = set(unapplied_rows(report))
    for name in _TASK_FIELDS:
        value = task.get(name)
        if _is_empty(value) or f"task.{name}" in skip:
            continue
        rows.append((f"task.{name}", _value_text(value, machine), _unit_of(name)))
    if task.get("type") == "molecular_dynamics":
        md = task.get("md") or {}
        for name in _MD_FIELDS:
            if not _is_empty(md.get(name)) and f"task.md.{name}" not in skip:
                rows.append((f"task.md.{name}", _value_text(md[name], machine), _unit_of(name)))
    if spec.kpoints is not None:
        kp = spec.kpoints.model_dump(mode="json")
        rows.append(("kpoints.mode", _value_text(kp["mode"]), ""))
        if kp["mode"] == "mesh":
            rows.append(("kpoints.mesh", "×".join(str(x) for x in kp["mesh"]), ""))
            rows.append(("kpoints.shift", _value_text(kp["shift"]), ""))
        elif kp["mode"] == "density":
            rows.append(("kpoints.density", _value_text(kp["density"]), "1/Å"))
    rows.append(("structure.source", _value_text(spec.structure.source, machine), ""))
    if spec.structure.source_ref.strip():
        ref = spec.structure.source_ref.strip()
        rows.append(("structure.source_ref", ref if len(ref) <= 120 else ref[:120] + " …", ""))
    if spec.plumed is not None:
        rows.append(("plumed", L("あり (plumed.dat。集合変数は利用者が書いたもの)",
                                 "yes (plumed.dat; the collective variables are the user's)"), ""))
    return rows


def _pw_in_pseudos(run_dir: Path) -> set[str]:
    path = run_dir / "pw.in"
    if not path.is_file():
        return set()
    names: set[str] = set()
    inside = False
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.upper().startswith("ATOMIC_SPECIES"):
            inside = True
            continue
        if inside:
            if line[0] in "&/" or line.split()[0].isupper() and len(line.split()) <= 2:
                break
            parts = line.split()
            if len(parts) >= 3:
                names.add(parts[2])
            else:
                break
    return names


def parameter_rows(report: RunReport) -> list[tuple[str, str, str]]:
    d = report.run_dir
    rows: list[tuple[str, str, str]] = []
    for path in sorted(d.rglob("*")):
        if not path.is_file():
            continue
        name = path.relative_to(d).as_posix()
        if path.suffix.upper() == ".UPF":
            from adit.codes.upf import UpfError, read_upf_header

            try:
                head = read_upf_header(path)
            except UpfError as ex:
                rows.append((name, L("ヘッダを読めません", "cannot read the header"), str(ex)))
                continue
            rows.append((name, head.element,
                         L(f"汎関数 {head.functional or '(記載なし)'}、価電子 {head.z_valence:g}、種類 {head.pseudo_type or '(記載なし)'}",
                           f"functional {head.functional or '(not stated)'}, valence {head.z_valence:g}, type {head.pseudo_type or '(not stated)'}")))
        elif path.suffix.lower() in (".pspnc", ".psp8", ".psp", ".fhi"):
            from adit.codes.abinit_psp import AbinitPspError, describe, read_psp_header

            try:
                psp = read_psp_header(path)
            except AbinitPspError as ex:
                rows.append((name, L("ヘッダを読めません", "cannot read the header"), str(ex)))
                continue
            rows.append((name, psp.title, describe(psp)))
        elif path.name == "POTCAR" or path.name.startswith("POTCAR"):
            from adit.codes.potcar import PotcarError, read_potcar_header

            try:
                head = read_potcar_header(path)
            except PotcarError as ex:
                rows.append((name, L("ヘッダを読めません", "cannot read the header"), str(ex)))
                continue
            rows.append((name, head.titel, L(f"価電子 {head.zval:g}、ENMAX {head.enmax:g} eV",
                                             f"valence {head.zval:g}, ENMAX {head.enmax:g} eV")))
    return rows


def parameter_notes(report: RunReport) -> list[str]:
    spec = report.spec
    if spec is None:
        return []
    out: list[str] = []
    method = spec.method.model_dump(mode="json")
    if spec.method.code == "espresso":
        referenced = sorted(set(method.get("pseudo", {}).values()) | _pw_in_pseudos(report.run_dir))
        missing = [n for n in referenced if not (report.run_dir / "pseudo" / n).is_file()]
        if missing:
            out.append(L(f"入力が参照する擬ポテンシャル {', '.join(missing)} は、このディレクトリにありません。"
                         "汎関数はファイルのヘッダにしか書かれていないので、この報告からは特定できません。",
                         f"the pseudopotentials referenced by the input ({', '.join(missing)}) are not in this directory; "
                         "the functional is recorded only in those files, so it cannot be identified from this report."))
    if spec.method.code == "vasp":
        out.append(L("VASP の POTCAR はライセンスのため生成先へ写しません。使った POTCAR の TITEL (汎関数を含む) は、"
                     "計算した環境の POTCAR か OUTCAR で確かめてください。",
                     "VASP POTCAR files are not copied into the generated directory for licensing reasons; check the TITEL "
                     "line (which names the functional) in the POTCAR or OUTCAR of the machine that ran the calculation."))
    if spec.method.code == "dftbplus":
        out.append(L("Slater-Koster のパラメータに交換相関汎関数の記載はありません (DFTB のパラメータ化そのものが近似です)。"
                     "使ったセットの名前と照合用のハッシュは上の表にあります。",
                     "Slater-Koster parameters record no exchange-correlation functional (the parameterization itself is the "
                     "approximation); the set name and fingerprints are in the table above."))
    return out


def runtime_rows(report: RunReport) -> list[tuple[str, str, str]]:
    spec = report.spec
    if spec is None:
        return []
    r = spec.runtime.model_dump(mode="json")
    rows = [("runtime.profile", _value_text(r["profile"]), ""),
            ("runtime.nodes", _value_text(r["nodes"]), ""),
            ("runtime.ncpus", _value_text(r["ncpus"]), ""),
            ("runtime.mpiprocs", _value_text(r["mpiprocs"]), L("プロセス", "processes")),
            ("runtime.omp_threads", _value_text(r["omp_threads"]), L("スレッド", "threads"))]
    if r.get("walltime"):
        rows.append(("runtime.walltime", _value_text(r["walltime"]), ""))
    return rows


def unapplied_rows(report: RunReport) -> dict[str, dict]:
    from adit.applied import unapplied_settings

    return unapplied_settings(report.spec) if report.spec is not None else {}


def structure_sentence(report: RunReport) -> str:
    spec = report.spec
    atoms = spec.atoms
    formula = atoms.get_chemical_formula()
    n = len(atoms)
    if all(atoms.pbc):
        cell = atoms.cell.cellpar()
        where = L(f"3 方向とも周期的なセル (a, b, c = {cell[0]:.4f}, {cell[1]:.4f}, {cell[2]:.4f} Å、"
                  f"α, β, γ = {cell[3]:.2f}, {cell[4]:.2f}, {cell[5]:.2f}°)",
                  f"a cell periodic in all three directions (a, b, c = {cell[0]:.4f}, {cell[1]:.4f}, {cell[2]:.4f} Å; "
                  f"α, β, γ = {cell[3]:.2f}, {cell[4]:.2f}, {cell[5]:.2f}°)")
    elif any(atoms.pbc):
        where = L(f"一部の方向だけ周期的なセル (pbc = {tuple(bool(x) for x in atoms.pbc)})",
                  f"a cell periodic in some directions only (pbc = {tuple(bool(x) for x in atoms.pbc)})")
    else:
        where = L("非周期 (孤立した分子)", "nonperiodic (an isolated molecule)")
    charge = L(f"全電荷 {spec.structure.charge}、スピン多重度 {spec.structure.multiplicity}",
               f"total charge {spec.structure.charge}, spin multiplicity {spec.structure.multiplicity}")
    return L(f"{formula} ({n} 原子、{where}、{charge})", f"{formula} ({n} atoms, {where}, {charge})")


_TASK_WORDS = {
    "single_point": ("一点計算", "a single-point calculation"),
    "geometry_optimization": ("構造最適化", "a geometry optimization"),
    "molecular_dynamics": ("分子動力学計算", "a molecular-dynamics run"),
    "vibrations": ("振動解析", "a vibrational analysis"),
    "band_structure": ("バンド計算", "a band-structure calculation"),
}


_SOURCE_WORDS = {
    "preset": ("ASE に入っている分子の形", "a molecule shipped with ASE"),
    "smiles": ("SMILES から RDKit が作った 3 次元構造", "3D coordinates built from SMILES by RDKit"),
    "file": ("読み込んだ構造ファイル", "a structure file that was read in"),
    "bulk": ("ASE の結晶の型から作ったバルク", "a bulk crystal built from an ASE prototype"),
    "spacegroup": ("空間群と分率座標から作った結晶", "a crystal built from a space group and fractional coordinates"),
    "surface": ("ASE の表面の関数で切ったスラブ", "a slab cut with an ASE surface function"),
    "mixture": ("溶液・混合物の詰め込み", "a packed solution or mixture"),
    "recipe": ("組み立て手順 (recipe) で作った構造", "a structure built from an assembly recipe"),
}


def structure_origin(report: RunReport) -> str:
    st = report.spec.structure
    how = _SOURCE_WORDS.get(st.source)
    what = L(*how) if how else st.source
    ref = st.source_ref.strip()
    if len(ref) > 200:
        ref = ref[:200] + L(" …(以下は spec.json の structure.source_ref)", " …(the rest is in structure.source_ref of spec.json)")
    if not ref:
        return L(f"構造の出典は、spec.json の記録では「{what}」です。",
                 f"The structure is recorded in spec.json as {what}.")
    return L(f"構造の出典は、spec.json の記録では「{what}」で、指定は {ref!r} です。",
             f"The structure is recorded in spec.json as {what}, with reference {ref!r}.")


def methods_sentence(report: RunReport) -> str:
    spec = report.spec
    task = _TASK_WORDS.get(spec.task.type, ("計算", "a calculation"))
    name = code_display_name(spec.method.code)
    version = report.code_version
    if version:
        version_text = L(f"{name} ({version})", f"{name} ({version})")
        source = L("バージョンは計算の出力から写したものです。", "The version was copied from the output of the run.")
    else:
        version_text = L(f"{name} (バージョンは未記録)", f"{name} (version not recorded)")
        source = L("バージョンは記録されていません (計算が終わっていないか、この計算コードのバージョンの行を確かめていません)。",
                   "The version is not recorded (the run has not finished, or the version line of this code was not verified).")
    prov = report.provenance
    made = ""
    if prov:
        made = L(f" 入力は ADIT {prov.get('adit_version', '?')} が {prov.get('generated_utc', '?')} (UTC) に生成しました。",
                 f" The input was generated by ADIT {prov.get('adit_version', '?')} on {prov.get('generated_utc', '?')} (UTC).")
    origin = structure_origin(report)
    return L(f"{structure_sentence(report)} について、{version_text} を用いて{L(*task)}を行いました。{source}{made} {origin}",
             f"For {structure_sentence(report)}, {L(*task)} was carried out with {version_text}. {source}{made} {origin}")


def _fingerprint_rows(report: RunReport) -> list[tuple[str, str, str]]:
    prov = report.provenance
    rows: list[tuple[str, str, str]] = []
    for item in prov.get("inputs") or []:
        rows.append((item["name"], item["sha256"], L("ADIT が生成した入力", "input generated by ADIT")))
    for item in prov.get("files") or []:
        rows.append((item["name"], item["sha256"], L("写したファイル (元の場所は spec.json の provenance)",
                                                     "copied file (its original path is in the provenance of spec.json)")))
    for item in prov.get("generated_files") or []:
        rows.append((item["name"], item["sha256"], L(f"書き写して作ったファイル (元の SHA-256: {item.get('source_sha256', '?')})",
                                                     f"file written from another (SHA-256 of the source: {item.get('source_sha256', '?')})")))
    return rows


def _table(header: tuple[str, ...], rows: list[tuple[str, ...]]) -> list[str]:
    if not rows:
        return []
    out = ["| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]
    out += ["| " + " | ".join(str(c).replace("|", "\\|") for c in row) + " |" for row in rows]
    return out + [""]


def methods_section(reports: list[RunReport]) -> list[str]:
    lines = [L("# 計算条件 (方法)", "# Computational details (methods)"), "",
             L("この文書は、ADIT が生成した計算ディレクトリの `spec.json`(作成時の記録つき) と `code_version.txt` から"
               "**記録に残っている事実だけ**を書き写したものです。"
               "記録が無い項目は「未記録」と書きます。推奨値や、ADIT が確かめていない説明は入れません。",
               "This document copies **only the facts that are on record** from the `spec.json` (with provenance) and "
               "`code_version.txt` in the directories generated by ADIT. "
               "Anything not on record is marked as not recorded. No recommended values or unverified statements are added."), ""]
    for i, report in enumerate(reports, 1):
        lines += [L(f"## {i}. {report.run_dir.name}", f"## {i}. {report.run_dir.name}"), "",
                  methods_sentence(report), ""]
        if not input_names(report):
            lines += [L("> **この計算の入力ファイルを特定できません。**照合用のハッシュの記録が無く、`spec.json` から作り直すこともできませんでした。"
                        "再現パッケージ (`--bundle`) にも入力は入りません。生成し直すか、入力を手で添えてください。",
                        "> **The input files of this run could not be identified.** No fingerprints are recorded and the inputs could not be "
                        "rebuilt from `spec.json`, so a `--bundle` package will not contain them. Regenerate the directory or attach the inputs by hand."), ""]
        rows = condition_rows(report)
        if rows:
            lines += [L("### 条件 (spec.json に記録された値)", "### Settings (as recorded in spec.json)"), ""]
            lines += _table((L("項目", "Field"), L("値", "Value"), L("単位", "Unit")), rows)
            lines += [L("空欄の項目と、値が 0 の方法の欄 (ADIT では「指定しない」の意味) は出していません。"
                        "**この表は `spec.json` の記録であって、計算コードの入力に実際に書かれたかは別です** "
                        "(共通の欄には、そのコードへ写されないものがあります)。実際に書かれた項目だけを照合するには "
                        "`adit-convert verify <ディレクトリ>` を使ってください "
                        "(読み戻して照合できるのは VASP・Quantum ESPRESSO・LAMMPS・GROMACS の入力だけです。"
                        "ほかのコードでは「未確認」となり、それは計算に問題があることを意味しません)。",
                        "Empty fields and method fields equal to 0 (which means 'not specified' here) are omitted. "
                        "**This table is what `spec.json` records, not proof of what was written into the code's input** "
                        "(some shared fields are not carried into every code). To compare only the settings that were actually "
                        "written, use `adit-convert verify <directory>` (only VASP, Quantum ESPRESSO, LAMMPS and GROMACS inputs can be "
                        "read back; for other codes the result is 'not verified', which does not mean anything is wrong with the run)."), ""]
        unapplied = unapplied_rows(report)
        if unapplied:
            lines += [L("### この計算コードの入力に書かれていない共通の欄",
                        "### Shared fields that are not written into this code's input"), ""]
            lines += _table((L("項目", "Field"), L("値", "Value"), L("理由", "Reason")),
                            [(name, _value_text(item["value"]), item["reason"]) for name, item in sorted(unapplied.items())])
            lines += [L("これらは `spec.json` に記録されていますが、上の入力には反映されていません (この表は `adit.applied` の、生成器を読んで確かめた一覧から作っています)。",
                        "These are recorded in `spec.json` but are not reflected in the input above (the list comes from `adit.applied`, compiled by reading the generators)."), ""]
        parameters = parameter_rows(report)
        notes = parameter_notes(report)
        if parameters or notes:
            lines += [L("### パラメータの出典 (擬ポテンシャルなど)", "### Parameter files (pseudopotentials and the like)"), ""]
            if parameters:
                lines += _table((L("ファイル", "File"), L("元素・名前", "Element / name"), L("ファイルに書かれていること", "What the file states")),
                                parameters)
            lines += [f"- {n}" for n in notes] + ([""] if notes else [])
        runtime = runtime_rows(report)
        if runtime:
            lines += [L("### 実行のしかた (spec.json の記録)", "### How it was run (as recorded in spec.json)"), ""]
            lines += _table((L("項目", "Field"), L("値", "Value"), L("単位", "Unit")), runtime)
            lines += [L("計算機の機種・OS・コンパイラ・数値ライブラリは ADIT が記録していないので、必要なら自分で書き足してください。",
                        "The machine, OS, compiler and numerical libraries are not recorded by ADIT; add them yourself if needed."), ""]
        fingerprints = _fingerprint_rows(report)
        if fingerprints:
            lines += [L("### 入力とパラメータの照合用のハッシュ (SHA-256)", "### Fingerprints of inputs and parameters (SHA-256)"), ""]
            lines += _table((L("ファイル", "File"), "SHA-256", L("種類", "Kind")), fingerprints)
            lines += [L("`adit-report <ディレクトリ> --check` で、いまのファイルがこの照合用のハッシュと同じかを確かめられます。",
                        "Run `adit-report <directory> --check` to confirm that the files still match these fingerprints."), ""]
        if report.analysis_summary:
            lines += [L("### 結果 (解析の要約)", "### Results (analysis summary)"), "",
                      L("`adit-analyze` が計算の出力から作った `analysis/summary.txt` をそのまま写しました "
                        "(値の出典は各行の注に書かれています)。",
                        "Copied verbatim from `analysis/summary.txt`, written by `adit-analyze` from the outputs of the run "
                        "(each line's note says where the value came from)."), "", "```"]
            lines += report.analysis_summary.splitlines()
            lines += ["```", ""]
            if lang.LANGUAGE == "en" and any("\u3040" <= ch <= "\u30ff" or "\u4e00" <= ch <= "\u9fff"
                                             for ch in report.analysis_summary):
                lines += ["The summary above is in Japanese because `adit-analyze` was run with the Japanese interface; "
                          "re-run it with `--lang en` (or `ADIT_LANG=en`) to get an English summary.", ""]
        if report.notes:
            lines += [L("### 記録が無いもの", "### Not on record"), ""]
            lines += [f"- {n}" for n in report.notes] + [""]
    return lines


def methods_markdown(reports: list[RunReport], language: str = "") -> str:
    if language not in ("ja", "en", "both", ""):
        raise ReportError(L(f"言語は ja / en / both のどれかにしてください: {language!r}",
                            f"the language must be ja, en or both: {language!r}"))
    if language in ("", lang.LANGUAGE):
        return "\n".join(methods_section(reports)) + "\n"
    before = lang.LANGUAGE
    try:
        if language == "both":
            lang.set_language("ja")
            text = "\n".join(methods_section(reports))
            lang.set_language("en")
            return text + "\n\n---\n\n" + "\n".join(methods_section(reports)) + "\n"
        lang.set_language(language)
        return "\n".join(methods_section(reports)) + "\n"
    finally:
        lang.set_language(before)


def conditions_csv(reports: list[RunReport]) -> str:
    rows: list[dict[str, str]] = []
    for report in reports:
        spec = report.spec
        row = {"run_dir": str(report.run_dir), "code": spec.method.code,
               "code_version": report.code_version,
               "formula": spec.atoms.get_chemical_formula(), "natoms": str(len(spec.atoms)),
               "periodic": "yes" if all(spec.atoms.pbc) else ("partial" if any(spec.atoms.pbc) else "no"),
               "charge": str(spec.structure.charge), "multiplicity": str(spec.structure.multiplicity),
               "adit_version": str(report.provenance.get("adit_version", ""))}
        for name, value, unit in condition_rows(report, machine=True):
            row[f"{name} [{unit}]" if unit else name] = value
        rows.append(row)
    columns: list[str] = []
    for row in rows:
        for key in row:
            if key not in columns:
                columns.append(key)
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=columns, lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow(row)
    return buf.getvalue()


def _short_version(text: str) -> str:
    words = text.split()
    return " ".join(words[:2]) if words else ""


def _analysis_values(run_dir: Path) -> dict[str, str]:
    path = Path(run_dir) / "analysis" / "summary.json"
    if not path.is_file():
        return {}
    try:
        tables = (json.loads(path.read_text(encoding="utf-8")) or {}).get("tables") or {}
    except ValueError:
        return {}
    out: dict[str, str] = {}
    msd = tables.get("msd") or {}
    if msd.get("D_cm2_s") is not None:
        out["diffusion_cm2_s"] = f"{float(msd['D_cm2_s']):.6g}"
    if (msd.get("D_error") or {}).get("d_err_cm2_s") is not None:
        out["diffusion_err_cm2_s"] = f"{float(msd['D_error']['d_err_cm2_s']):.6g}"
    if msd.get("loglog_slope") is not None:
        out["msd_loglog_slope"] = f"{float(msd['loglog_slope']):.4g}"
    visc = tables.get("viscosity") or {}
    if visc.get("eta_mpa_s") is not None:
        out["viscosity_mpa_s"] = f"{float(visc['eta_mpa_s']):.6g}"
    return out


def results_csv(reports: list[RunReport]) -> str:
    from adit.analysis.readers import load_run
    from adit.results import not_run_yet, summarize_run

    rows: list[dict[str, str]] = []
    for report in reports:
        spec = report.spec
        row = {"run_dir": str(report.run_dir), "code": spec.method.code,
               "code_version": report.code_version, "code_version_short": _short_version(report.code_version),
               "task": spec.task.type, "formula": spec.atoms.get_chemical_formula(), "natoms": str(len(spec.atoms)),
               "state": "", "finished": "", "converged": "", "steps": "",
               "final_energy_ev": "", "energy_points": "", "temperature_mean_k": "", "frames": "",
               "frequencies": "", "diffusion_cm2_s": "", "diffusion_err_cm2_s": "", "msd_loglog_slope": "",
               "viscosity_mpa_s": "", "note": ""}
        if not_run_yet(report.run_dir):
            row["state"] = "not_run"
            row["note"] = L("計算の出力がありません", "no output of a calculation")
            rows.append(row)
            continue
        try:
            data = load_run(report.run_dir)
        except Exception as ex:
            from adit.results import failure_note

            row["state"] = "unreadable"
            row["note"] = " ".join(x for x in (str(ex), failure_note(report.run_dir, spec.method.code)) if x)
            rows.append(row)
            continue
        row["state"] = "read"
        if data.energies_ev:
            row["final_energy_ev"] = f"{data.energies_ev[-1]:.10g}"
            row["energy_points"] = str(len(data.energies_ev))
        if data.temperatures_k:
            import numpy as np

            row["temperature_mean_k"] = f"{float(np.mean(data.temperatures_k)):.6g}"
        if data.frames:
            row["frames"] = str(len(data.frames))
        if data.frequencies_cm1:
            row["frequencies"] = str(len(data.frequencies_cm1))
        try:
            summary = summarize_run(report.run_dir)
            row["finished"] = "" if summary.finished is None else ("true" if summary.finished else "false")
            row["converged"] = ("true" if summary.converged else "false") if spec.task.type == "geometry_optimization" else ""
            row["steps"] = str(summary.geometry_steps)
            if not summary.completion_assessed:
                row["finished"] = "unknown"
        except Exception as ex:
            row["note"] = str(ex)
        row.update(_analysis_values(report.run_dir))
        from adit.results import failure_note

        stopped = failure_note(report.run_dir, spec.method.code)
        if stopped:
            row["state"] = "stopped_with_message"
            row["note"] = f"{row['note']} {stopped}".strip()
        rows.append(row)
    if len({row["code"] for row in rows}) > 1:
        caveat = L("コードが混ざった表です。final_energy_ev の絶対値はコード間で比べられません (基準が違う)",
                   "this table mixes codes; the absolute final_energy_ev cannot be compared between codes (different references)")
        for row in rows:
            if row["final_energy_ev"]:
                row["note"] = f"{caveat}。{row['note']}" if row["note"] else caveat
    columns = list(rows[0]) if rows else []
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=columns, lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow(row)
    return buf.getvalue()


def input_names(report: RunReport) -> list[str]:
    recorded = [item["name"] for item in (report.provenance.get("inputs") or [])]
    if recorded:
        return recorded
    try:
        from adit.config import load_config
        from adit.project import build_project

        names = sorted(build_project(report.spec, load_config()).texts)
    except Exception:
        report.notes.append(L("入力の照合用のハッシュの記録が無く、spec.json から作り直すこともできないので、入力ファイルの一覧は分かりません",
                              "the input fingerprints are not recorded and the inputs cannot be rebuilt from spec.json, so the list of input files is unknown"))
        return []
    report.notes.append(L("入力の照合用のハッシュの記録が無いので、spec.json から作り直して入力ファイルの名前だけを求めました (中身は突き合わせていません)",
                          "the input fingerprints are not recorded, so the input file names were obtained by rebuilding from spec.json (the contents were not compared)"))
    return [n for n in names if (report.run_dir / n).is_file()]


def bundle_files(report: RunReport) -> list[str]:
    names = ["spec.json", "README.txt", "submit.sh", "code_version.txt"]
    names += input_names(report)
    for item in (report.provenance.get("files") or []) + (report.provenance.get("generated_files") or []):
        names.append(item["name"])
    seen, out = set(), []
    for name in names:
        if name in seen or not (report.run_dir / name).is_file():
            continue
        seen.add(name)
        out.append(name)
    return out


def manifest(reports: list[RunReport]) -> dict:
    from adit import __version__

    runs = []
    for report in reports:
        checks = {item["name"]: item for item in verify_inputs(report.run_dir)}
        files = []
        for name in bundle_files(report):
            entry = {"name": name, "sha256": sha256_file(report.run_dir / name)}
            if name in checks:
                entry["recorded_sha256"] = checks[name]["recorded"]
                entry["state"] = checks[name]["state"]
            files.append(entry)
        runs.append({"run_dir": str(report.run_dir), "code": report.code,
                     "code_version": report.code_version, "provenance": report.provenance,
                     "files": files, "not_on_record": report.notes})
    return {"adit_version": __version__, "runs": runs,
            "note": L("files の sha256 はこの package を作ったときに計算した値、recorded_sha256 は入力を生成したときに記録した値です。",
                      "sha256 is computed when this package was made; recorded_sha256 is what was stored when the input was generated.")}


def write_bundle(reports: list[RunReport], dest: Path | str, *, language: str = "") -> Path:
    out = Path(dest).expanduser()
    if out.exists():
        raise ReportError(L(f"すでにあります: {out} (別の名前を指定してください。上書きはしません)",
                            f"already exists: {out} (choose another name; nothing is overwritten)"))
    methods = methods_markdown(reports, language)
    data = json.dumps(manifest(reports), indent=2, ensure_ascii=False) + "\n"
    if out.suffix.lower() == ".zip":
        with zipfile.ZipFile(out, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.writestr(METHODS_FILE, methods)
            zf.writestr(MANIFEST_FILE, data)
            for report in reports:
                for name in bundle_files(report):
                    zf.write(report.run_dir / name, f"{report.run_dir.name}/{name}")
        return out
    out.mkdir(parents=True)
    (out / METHODS_FILE).write_text(methods, encoding="utf-8")
    (out / MANIFEST_FILE).write_text(data, encoding="utf-8")
    for report in reports:
        target = out / report.run_dir.name
        for name in bundle_files(report):
            (target / name).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(report.run_dir / name, target / name)
    return out


_KIND_WORDS = {"input": ("生成した入力", "generated input"),
               "copied": ("写したファイル", "copied file"),
               "written": ("書き写したファイル", "file written from another")}


def check_lines(report: RunReport) -> tuple[list[str], str]:
    results = verify_inputs(report.run_dir)
    if not results:
        made = (report.provenance or {}).get("generated_utc")
        when = L(f" (spec.json に記録されている生成日時: {made})", f" (generation time on record: {made})") if made else ""
        return ([L(f"{report.run_dir}: 照合用のハッシュの記録がないので確かめられません。この spec.json には入力の SHA-256 がありません{when}",
                   f"{report.run_dir}: cannot check — this spec.json records no input fingerprints{when}")],
                "unknown")
    lines = []
    changed = missing = replaced = 0
    for item in results:
        kind = L(*_KIND_WORDS.get(item["kind"], ("", "")))
        if item["state"] == "same":
            lines.append(L(f"  同じ      {item['name']}  ({kind})", f"  same      {item['name']}  ({kind})"))
        elif item["state"] == "replaced_at_run":
            replaced += 1
            lines.append(L(f"  引き継ぎ  {item['name']}  ({kind}。前の段階の出力で置き換わりました)",
                           f"  handed on {item['name']}  ({kind}; replaced by the previous stage's output)"))
        elif item["state"] == "changed":
            changed += 1
            lines.append(L(f"  書き換え  {item['name']}  ({kind}。記録 {item['recorded'][:12]}… → いま {item['found'][:12]}…)",
                           f"  changed   {item['name']}  ({kind}; recorded {item['recorded'][:12]}… → now {item['found'][:12]}…)"))
        else:
            missing += 1
            lines.append(L(f"  ありません {item['name']}  ({kind})", f"  missing   {item['name']}  ({kind})"))
    head = L(f"{report.run_dir}: 生成したときの照合用のハッシュと突き合わせました ({len(results)} 件)",
             f"{report.run_dir}: compared with the fingerprints recorded at generation ({len(results)} files)")
    if not (changed or missing):
        tail = [L("  → すべて生成したときのままです", "  → all files are as generated")]
        if replaced:
            tail.append(L(f"  ({replaced} 件は、段階に分けた計算で前の段階の出力に置き換わったものです。submit.sh がそう書いています)",
                          f"  ({replaced} file(s) were replaced by the previous stage's output, as submit.sh prescribes)"))
        verdict = "ok"
    else:
        parts = []
        if changed:
            parts.append(L(f"書き換えられたファイル {changed} 件", f"{changed} file(s) changed"))
        if missing:
            parts.append(L(f"無くなったファイル {missing} 件", f"{missing} file(s) missing"))
        tail = [L(f"  → {'、'.join(parts)}。この計算の条件は spec.json の記録と違うかもしれません。",
                  f"  → {', '.join(parts)}. The settings of this run may differ from what spec.json records.")]
        verdict = "bad"
    return ([head] + lines + tail, verdict)


# ---------------- CLI ----------------
def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="adit-report",
        description=L("ADIT が生成した計算ディレクトリから、方法の節・条件の表・入力の照合用のハッシュを書き出します",
                      "Write the methods section, settings table and input fingerprints of directories generated by ADIT"))
    p.add_argument("run_dirs", nargs="+", help=L("計算ディレクトリ (spec.json のある場所)", "calculation directories (where spec.json is)"))
    p.add_argument("-o", "--out", metavar="methods.md", help=L("方法の節の書き出し先 (既定は画面)", "where to write the methods section (default: screen)"))
    p.add_argument("--lang", choices=("ja", "en", "both"), default="", help=L("報告の言語 (既定は ADIT の設定)", "language of the report (default: the ADIT setting)"))
    p.add_argument("--csv", metavar="conditions.csv", help=L("条件の表を CSV で書き出します", "write the settings table as CSV"))
    p.add_argument("--results-csv", metavar="results.csv", help=L(
        "複数の計算の結果 (最終エネルギー・平均温度・正常終了・収束など) を 1 枚の表にします",
        "write the results of several runs (final energy, mean temperature, completion, convergence) as one table"))
    p.add_argument("--bundle", metavar="pack.zip", help=L("再現に要るファイルと manifest.json をまとめます (.zip かディレクトリ)",
                                                          "collect the files needed to reproduce plus manifest.json (.zip or a directory)"))
    p.add_argument("--check", action="store_true", help=L(
        "生成したときの照合用のハッシュと、いまのファイル (入力・写した擬ポテンシャルや力場) を突き合わせます。終了コード 0 = 一致、1 = 不一致、2 = 記録が無くて確かめられない",
        "compare the current files (inputs and copied pseudopotentials or force fields) with the fingerprints recorded at generation; "
        "exit code 0 = all match, 1 = mismatch, 2 = nothing on record to check against"))
    args = p.parse_args(argv)
    try:
        reports = [load_run_report(d) for d in args.run_dirs]
    except ReportError as ex:
        print(str(ex))
        return 2
    if args.check:
        verdicts = []
        for report in reports:
            lines, verdict = check_lines(report)
            verdicts.append(verdict)
            print("\n".join(lines))
        if "bad" in verdicts:
            return 1
        if "unknown" in verdicts:
            print(L("照合用のハッシュの記録が無いディレクトリがあるので、一致は確かめられていません (終了コード 2)。",
                    "Some directories have no recorded fingerprints, so nothing could be confirmed (exit code 2)."))
            return 2
        return 0
    try:
        if args.csv:
            Path(args.csv).expanduser().write_text(conditions_csv(reports), encoding="utf-8")
            print(L(f"条件の表を書きました: {args.csv}", f"wrote the settings table: {args.csv}"))
        if args.results_csv:
            Path(args.results_csv).expanduser().write_text(results_csv(reports), encoding="utf-8")
            print(L(f"結果の表を書きました: {args.results_csv}", f"wrote the results table: {args.results_csv}"))
        if args.bundle:
            out = write_bundle(reports, args.bundle, language=args.lang)
            print(L(f"再現パッケージを書きました: {out}", f"wrote the reproducibility package: {out}"))
        text = methods_markdown(reports, args.lang)
    except ReportError as ex:
        print(str(ex))
        return 2
    if args.out:
        Path(args.out).expanduser().write_text(text, encoding="utf-8")
        print(L(f"方法の節を書きました: {args.out}", f"wrote the methods section: {args.out}"))
    elif not (args.csv or args.bundle or args.results_csv):
        print(text, end="")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
